README.md, onyo/commands/__init__.py, onyo/commands/anchor.py, onyo/commands/new.py, onyo/commands/unanchor.py, onyo/main.py, onyo/utils.py, setup.py, tests/default_tests.py
To use the same function in (un)anchor like in `onyo new`, code from new.py got moved to utils.py.
At this point I normalized the variable `location` also to `directory` in `onyo new`.
Implements `anchor` and `unanchor` as subcommands to `onyo`.
Adds anchor/unanchor to the tests.
anchor and unanchor are explained in README.md.
Sets minimum python version to 3.5 in setup.py.
=> Add onyo anchor, unanchor

README.md
This PR fixes an ambiguity in the design of `onyo get`, and implements option 4 proposed in issue #30.
This PR also includes a fix for a nit I found in the usage syntax of `onyo get` and `onyo set`.
=> `onyo get`: multiple keys must be comma separated

onyo/commands/__init__.py, onyo/commands/git.py, onyo/main.py, onyo/utils.py, tests/default_tests.py
utils and tests use shlex.split(cmd) instead of cmd.split() because
shlex does not split at all spaces, but respects quotes, too.
=> onyo git: add function, parameters, tests

.github/workflows/main.yml, onyo/utils.py, setup.py, tests/default_tests.py, tests/output_goals/test_1/init_test.txt, tests/output_goals/test_2/init_test.txt, tests/output_goals/test_3/init_test.txt, tests/output_goals/test_4/init_test.txt
Instead of using a hardcoded file path, the default_tests.py uses the location relative to itself to find the files to compare the ouput to, and to creates a folder to run all the tests in. Instead of using a set path in the output files, replaces paths in the output with a path for each test, depending on the location the test was run from.
Sets up a github action file to run the tests automatically for each push.
=> tests: runable from other directories/systems; adds github action to run tests automatically

README.md
This works towards #9 
This intentionally does not add a `--recursive` flag. `onyo tree` already meets that use-case well, and scripts should use `onyo get` rather than `onyo ls`.
I intentionally used the words "files" and "directories", because I think `onyo ls` should include files/dirs that are non-assets (as opposed to `onyo get`, which should only query/open assets).
I left the output undefined, as I didn't feel it was appropriate for a user-facing doc. IMO, directories should be suffixed with a `/`. Colors should be used to differentiate between:
- assets (either file or dir) 
- non-asset files
- unanchored dirs
- anchored dirs
A separate issue for colorizing `onyo ls` (and possibly other) output would probably be most appropriate, to keep this manageable.
Feedback is much …
=> design onyo ls

onyo/commands/cat.py, onyo/commands/edit.py, onyo/commands/mkdir.py, onyo/commands/mv.py, onyo/commands/new.py, onyo/commands/rm.py, onyo/commands/tree.py, onyo/main.py, onyo/utils.py, tests/default_tests.py
The commands that can get multiple inputs check all of them now before running any operation, so onyo can inform about problems beforehand, and then after running all operations, onyo creates 1 commit (before, it did one commit per changed/created file/folder).
During this, some commands (like edit) got changed and do now accept multiple inputs. This is part of the PR, so the check_sources() functions do not have to be done first for one source, and then re-written for multiple ones.
=> Check files before running command(s), create one commit per command

.flake8, onyo/commands/edit.py, onyo/commands/mkdir.py, onyo/commands/mv.py, onyo/commands/new.py, onyo/commands/rm.py, onyo/commands/tree.py, onyo/utils.py
This PR contains a lot of little changes, cleanups and movings of code, that were put of "for later", in issues and video meetings.
`onyo edit` checks if the editor set by $EDITOR exists, if not, if nano exists and newly, uses now vi as a fallback, in case nano is not found, too. Using vi as a fallback was in the readme for a long time and now is finally part of the code.
The other changes are updates of output (like errors), and renaming of variables and functions in the code.
=> Cleanup code

onyo/commands/cat.py, onyo/commands/edit.py, onyo/commands/git.py, onyo/commands/init.py, onyo/commands/mkdir.py, onyo/commands/mv.py, onyo/commands/new.py, onyo/commands/rm.py, onyo/commands/tree.py, onyo/main.py, tests/default_tests.py, tests/output_goals/test_tree_output.txt
This PR changes onyo, so that now the onyo directory, in which to run all the commands is decided on the main level of onyo to simplify the code and `onyo fsck` in the future. The possibility to run onyo from outside of the onyo directory with relative paths that lead into the onyo directory is removed, instead the user has either to set the environmental variable or be in the right directory.
This contains also all the implied changes (e.g. variable names, tests).
=> all commands: move decision for onyo directory to main.py

onyo/commands/edit.py, onyo/commands/init.py, onyo/commands/new.py, onyo/utils.py
This adds to `onyo edit` a yaml check, so that the command cannot messup a file and automatically saves it (since this would block the next onyo command if it starts with an fsck). This is realized with a temp file, which is created by copying the file which should be edited, then changes that file, and afterwards, if the new file has correct yaml syntax, moves it back to the right location.
`onyo init´ got the addition of creating and anchoring the now needed folder `.onyo/temp/`.
There are multiple other checks and questions, like "exists a temp file for this to beginn with?" and "does the user wants to further edit or discard the syntax breaking changes?".
The files are just under `.onyo/temp/asset`, without further folders. This works because the asset files have to be unique (per …
=> Edit: do a syntax check after change (with temp file)

MANIFEST.in, README.md, onyo/commands/edit.py, onyo/commands/fsck.py, onyo/commands/init.py, onyo/commands/mv.py, onyo/commands/new.py, onyo/utils.py, onyo/validation/validation.yaml, setup.py
Hey, I am currently working on the implementation of the validation system.
On the one hand, I am starting with something simple as a proof of concept to make sure everything *can work*, on the other hand I write it so that it can be expanded as much as we want with addtional keys, functionalities etc.
So to give a chance to discuss the validation system how I currently implemented (or still implement) it before creating a PR, I want to show what I have and request comments, in case something is not as discussed earlier.
First, I have a file `.onyo/validation/field_names.rules` (I know the name is bad. I wish no critic about it, but better names are very welcome). I used RAM and Size as 2 different field names, just as examples to work with, but the key names can be choosen freely.
``` …
```
=> Validation

onyo/commands/__init__.py, onyo/commands/set.py, onyo/main.py
This enables to set one or multiple values for one or multiple assets.
It changes existing values, or adds new ones.
The flags --rename and --filter are still missing and must be
added later. Dictionary keys and lists as values are not implemented.
Close #108 because it implements the changes discussed.
Close #15 because the command is implemented.
Issues about the missing flags and functionalities will be added,
together with a cleanup of the readme.
=> set: add command to onyo

onyo/commands/config.py, onyo/commands/fsck.py, onyo/commands/history.py, onyo/commands/mkdir.py, onyo/commands/mv.py, onyo/commands/new.py, onyo/commands/rm.py, onyo/commands/set.py, onyo/main.py, onyo/utils.py
Most commands should be possible to run from inside a folder like
`shelf/` or `user\ nr\ 2/` and with relative paths.
Because additional functions like validation got added to onyo and
other functions like the environmental variable got removed,
not all possible combinations were possible anymore.
This commit allows for many commands that they can be run from
inside a folder like shelf/ (e.g. when in shelf/ `onyo new .`
creates an asset in the folder shelf/) and run the validation
on it, or calling onyo config from inside a directory, onyo mv
with relative paths, etc.
During the above mentioned changes I also noticed, that sometimes
the internally used commands `git -C <onyo_dir> commit` missed to
have quotes in the newer functions around <onyo_dir>, which could
also lead to errors when …
=> onyo: run commands inside folder e.g. shelf/, fix "spaces in paths" errors

onyo/commands/git.py, onyo/main.py
This is a collection of various improvements the the help output. Including:
- assorted string fixes
- fix an incorrect help string (fixes #128)
- reduced noise of argparse's default output (fixes #132)
- alphabetizes help output (fixes #130)
- retire `onyo git -C` (fixes #133)
The last one is unrelated to help text, but I was in the area anyways.
=> improvements to help text

README.md, onyo/commands/__init__.py, onyo/commands/shell_completion.py, onyo/main.py
Works towards #28
This adds a tab completion script for bash and zsh that works for 90-95% of situations. It's a bit ugly, and I have talked myself into an alternative approach that will be more maintainable, faster, and better able to handle the corner cases I've discovered.
However, this does work, and may be of value to people who desire this functionality now.
To use, simply:
```
source <(onyo shell-completion)
```
=> add `onyo shell-completion` command for bash and zsh tab-completion

.github/workflows/main.yml
It was removed in a previous PR (#131), but PyPy3 is compatible with CPython 3.7 and 3.8 (both of which Onyo still supports).
This updates the Python environment used by GitHub Actions, and uses the new pypy<x>.<y> syntax to denote version (the previous generic "pypy3" was compatible with CPython 3.6).
=> tests: re-enable pypy3

README.md
Fix some "it's" -> "its". Also alphabetize the order of onyo commands.
=> DOC: readme fixes

onyo/commands/set.py, tests/output_goals/test 1/cat_output.txt, tests/output_goals/test 2/cat_output.txt
This puts YAML in "round-trip" mode.
Fix #158
=> set: preserve comments and order when writing

onyo/__init__.py, onyo/_version.py, onyo/utils.py, setup.py
This PR moves the version number out of `setup.py` and into a location addressable by the rest of Onyo. And then the `--version` flag is added, addressing #137.
=> add --version flag

docs/source/index.rst, docs/source/installation.rst, docs/source/introduction.rst
Right now, I don't think we need an introduction page. Instead, I've added a page with installation instructions. Then eventually a quickstart or common work-flows page might make sense to add.
With this change, I think the docs are ready to go live with Read the Docs.
=> DOC: add installation instructions and remove empty introduction page

onyo/commands/mkdir.py, tests/test_main.py, tests/test_mkdir.py
This reduces the number of functions from 5 to 3, adds docstrings, and overall simplifies the logic and var names.
Ideally the dir names would be all relative to the root of the onyo repository. A TODO has been added about this.
It would also be more performant to build a list of anchors and add them all in one call, rather than invoke a new process for each add. But I don't see people adding 10k directories at once, so I figured it best to leave the code simple as it is.
=> Refactor `mkdir`

setup.py, tests/test_shell-completion.py
While testing mkdir, I discovered that it ignores chdirs from fixtures. That was quite annoying to troubleshoot.
Their documentation isn't good, and it's not buying us much. Choosing to keep it simple and use what's in the standard library.
=> TST: drop dep pytest-shell-utilities

tests/test_init.py
I wrote the guard but not the test. This gets it to 100% coverage.
=> TST: add a missing test to "init"

.github/workflows/main.yml, .gitignore, README.md, codecov.yaml, tests/conftest.py
This is just a collection of stuff that makes life a bit nicer when developing Onyo:
- `.gitignore`
- re-enable the codecov bot (I unintentionally disabled this before, it seems)
- auto-clean the "sandbox" (the directory where tests execute)
=> TST: some quality of life improvements

onyo/utils.py
This is a very imperfect solution. But it's the most readily available one, and our needs are not (yet) complicated. I would /love/ for there to be a "plaintext" docutils writer.
Fixes #154
=> DOC: strip rst formatting from description text

onyo/commands/shell_completion.py, onyo/utils.py, tests/conftest.py
Reorganize the code for `shell-completion` for readability and consistency. It also lays down the groundwork to add support for other shells (see #155).
=> shell-completion: refactor

.github/workflows/main.yml, README.md, docs/source/configuration.rst, docs/source/index.rst, onyo/__init__.py, onyo/commands/config.py, onyo/commands/edit.py, onyo/commands/history.py, onyo/commands/new.py, onyo/main.py, onyo/skel/config, onyo/utils.py, tests/conftest.py, tests/test_config.py, tests/test_utils.py
This PR:
- rewrites `onyo config`, basically turning it into a wrapper for `git config -f .onyo/config`
- adds tests
- adds documentation
- moves all configuration options to an "onyo" namespace, so that they can be set in git without fear of conflict
- the editor spawned by onyo is now configurable via `onyo.core.editor`
- adds a function `get_config_value()` to simplify and improve support in the codebase for using config values
=> RF: `config`

docs/source/cmd_cat.rst, docs/source/cmd_config.rst, docs/source/cmd_edit.rst, docs/source/cmd_fsck.rst, docs/source/cmd_history.rst, docs/source/cmd_init.rst, docs/source/cmd_mkdir.rst, docs/source/cmd_mv.rst, docs/source/cmd_new.rst, docs/source/cmd_onyo.rst, docs/source/cmd_rm.rst, docs/source/cmd_set.rst, docs/source/cmd_shell-completion.rst, docs/source/cmd_tree.rst, onyo/commands/shell_completion.py, onyo/main.py, onyo/utils.py, tests/commands/test_onyo.py, tests/conftest.py, tests/test_main.py
This PR refactors main, improves its readability, adds tests and docstrings, and fixes multiple bugs.
The tests focus on behavior when invoking  `onyo` itself and its flags. Helper functions are also added, which should be useful for other tests which could benefit from [powersets](https://en.wikipedia.org/wiki/Power_set).
Bugs fixed:
- insufficient number of args to onyo would still exit 0
- args named 'config' to subcommands would result in subsequent args being ignored
- onyo -d -C /tmp (and similar) would crash with Python trace
=> RF: onyo invocation; add tests

onyo/commands/new.py, onyo/utils.py, tests/commands/test_new.py, tests/test_utils.py
Changes in `onyo new`:
- uses pathlib.Path, shutil, and git.Repo
- updates imports
- adds doc-strings, f-strings and more whitespace
- adds minimal tests for `onyo new`
- at different folder depths
- white and without spaces in name
- with and without faux serial
Changes in `utils`:
- modernize `edit_file()` (pathlib, doc-strings, f-strings)
- refactor `utils.get_list_of_assets()`
- move code `create_faux()` from `new` to `utils` and rename the function to `generate_faux_serial()`
- use `random.choices()` instead of `uuid1()` for the creation of faux serial numbers
- add also pathlib, doc-strings and f-strings
- test `generate_faux_serial()`
- check for generation of different faux numbers with default length
- test generation of different faux serial numbers with varying length
- test …
=> RF/TST (pathlib, doc-strings, f-strings): `new`; `utils.edit_file()` and `utils.generate_faux_serial()`, `utils.get_list_of_assets()`

.github/workflows/main.yml, README.md, docs/source/installation.rst, onyo/commands/history.py, setup.py
Debian stable (bullseye), latest macOS (12), and PyPy all support Python 3.9.
Bumping this will help with the soon-to-arrive type hinting efforts (#222) and reduce the number of compute minutes we use on the free-tier for GitHub Actions.
=> bump Python baseline 3.7 -> 3.9

.github/workflows/main.yml
Otherwise PRs from in-repo branches run twice.
=> TST: only run push on main

onyo/commands/cat.py, onyo/commands/config.py, onyo/commands/edit.py, onyo/commands/fsck.py, onyo/commands/history.py, onyo/commands/mkdir.py, onyo/commands/mv.py, onyo/commands/new.py, onyo/commands/rm.py, onyo/commands/set.py, onyo/commands/tree.py, onyo/lib/__init__.py, onyo/lib/onyo.py, tests/lib/test_Repo.py, tests/lib/test_Repo_add.py, tests/lib/test_Repo_commit.py, tests/lib/test_Repo_fsck.py, tests/lib/test_Repo_mkdir.py
Notable changes:
- introduce `Repo().add()` (with tests)
- introduce `Repo().commit()` (with tests)
- introduce `Repo().mkdir()` (with tests)
- convert `mkdir` to use `Repo().mkdir()`
- convert most commands to use `add()` and `commit()`
Tests for the command `mkdir` have been left intact. Those (along with the others) will eventually be reduced and simplified to focus on the user experience (output, prompts, exit codes, etc) rather than the functionality (which is well covered in the method tests). However, it does not make sense to begin this effort yet until the rework of the logging system happens.
=> NF/RF: Repo.add(), Repo.commit(), mkdir -> Repo.mkdir()

onyo/lib/onyo.py, tests/commands/test_mv.py, tests/commands/test_new.py, tests/commands/test_rm.py, tests/conftest.py, tests/lib/test_Repo.py, tests/lib/test_Repo_fsck.py, tests/lib/test_Repo_mkdir.py
This adds a helper, and simplifies some of the number of files and dirs being created by tests.
This drops overall test runtime by 15%. This is likely due to fewer subshells being spawned, and a reduction in overall work.
Also, I uncovered a bug in `mkdir` as part of the refactoring.
=> TST/RF: add populate_repo() helper

.flake8, .github/workflows/main.yml, README.md, onyo/lib/onyo.py, pytest.ini, tests/commands/test_config.py, tests/commands/test_history.py, tests/conftest.py, tests/lib/test_Repo.py, tests/lib/test_Repo_add.py, tests/lib/test_Repo_commit.py, tests/lib/test_Repo_fsck.py, tests/lib/test_Repo_mkdir.py, tests/test_utils.py
This leverages many new (to this codebase) pytest features.
Most notably, the introduction of a `repo` fixture. This fixture:
- creates a new repository in a temporary directory
- `cd`s into the dir
- returns a handle to the repo
Furthermore, it will populate the repository by looking for the following markers:
- repo_dirs()
- repo_files()
- files automatically have their parent dirs created.
Parameterization is now used, reducing repetitive tests.
All of this works towards:
- the eventual retirement of `change_cwd_to_sandbox`, `clean_sandboxes`, and `populate_repo`.
- parallel execution of tests
- randomization of test order
The modernizing in the PR is limited to the newer portions of the tests. The rest will be addressed as work continues to bring more functionality into the `Repo` …
=> TST/RF: leverage pytest features

onyo/commands/rm.py, onyo/lib/onyo.py, tests/lib/test_Repo_commit.py, tests/lib/test_Repo_fsck.py, tests/lib/test_Repo_rm.py, tests/reference_output/C_absolute/delete_device.txt, tests/reference_output/root_of_repo/delete_device.txt
Notable changes:
- introduce `Repo().rm()` (with tests)
- convert `rm` to use `Repo().rm()`
- add tests for a few corner cases in `fsck()` and `commit()`
As with the other conversion, the tests for the command `rm` have been left intact. They will be address later when the logging overhaul happens.
=> NF/RF: rm -> Repo.rm() (and a few unrelated tests)

tests/commands/test_history.py
Change command calls from e.g. `/bin/printf` to `/usr/bin/env printf` to use tests platform independent.
`test_history.py` used built-in commands e.g. `/bin/printf`. These differ on macbooks (e.g. `/usr/bin/printf`) so the tests for the `onyo history` command failed on macOS.
=> TST/BF: make test_history.py platform independent

.github/workflows/main.yml
It takes ~5x longer to run, and burns up minutes that we could use for better purposes.
I considered adding macOS, but at a 10x premium, that means we have 200 minutes of tests per month.  And that's just macOS, and not including the other 3 platforms.
=> TST: remove pypy

onyo/commands/mv.py, onyo/lib/onyo.py, tests/commands/test_mv.py, tests/lib/test_Repo_mv.py, tests/lib/test_Repo_rm.py
Notable changes:
- introduce `Repo().mv()` (with tests)
- add a bunch of new tests, covering a lot of corner cases
- fix bugs around explicit move (`file-1` -> `subdir/file-1`)
As with the other conversion, the tests for the command `mv` have been left intact. They will be address later when the logging overhaul happens.
=> NF/RF: mv -> Repo.mv() ; add tests

onyo/commands/cat.py, onyo/commands/config.py, onyo/commands/edit.py, onyo/commands/fsck.py, onyo/commands/history.py, onyo/commands/init.py, onyo/commands/mkdir.py, onyo/commands/mv.py, onyo/commands/new.py, onyo/commands/rm.py, onyo/commands/set.py, onyo/commands/shell_completion.py, onyo/commands/tree.py, onyo/main.py, onyo/utils.py, tests/conftest.py, tests/reference_output/C_absolute/test_tree_output.txt, tests/reference_output/root_of_repo/test_tree_output.txt, tests/test_utils.py
This is a collection of seeming-random, but actually interconnected changes.
Changed of note:
- quick-and-dirty modernization of `tree`. No thought was put into repo-ification, which also seems largely unneeded
- renaming of `onyo_root` to either `opdir` (which is what it usually means) or `repo_root` (which it sometimes means)
- update the `utils.py` tests to use the `repo` fixture and update some comments
- finally drop `run_cmd()`, `build_git_add_cmd()`, and `get_git_root()` from utils, as the above were the last consumers.
=> WIP: TST/RF: assorted cleanup

onyo/commands/mkdir.py, onyo/commands/mv.py, onyo/commands/rm.py, onyo/lib/onyo.py, tests/conftest.py, tests/lib/test_Repo_mkdir.py, tests/lib/test_Repo_mv.py, tests/lib/test_Repo_rm.py
This updates the following to stage changes and not commit them:
- `mkdir()`
- `mv()`
- `rm()`
Note, this only changes the methods. The /commands/ have been updated to commit the changes.
This also updates the tests to check the new behavior.
=> NF: Repo() methods should stage changes

onyo/commands/init.py, onyo/lib/onyo.py, setup.py, tests/commands/test_cat.py, tests/commands/test_history.py, tests/conftest.py, tests/lib/test_Repo.py, tests/lib/test_Repo_new.py, tests/reference_output/C_absolute/init_test.txt, tests/reference_output/root_of_repo/init_test.txt
This PR covers a variety of areas:
Notable changes:
- add `Repo(init=True)` with tests
- port `init` and test helpers to use `Repo(init=True)`
- drop GitPython as a dependency
- `generate_faux_serials()` will only generate > 0 serials
- expand and improve tests for `generate_faux_serials()`
- update tests for `history` and `cat` to use the `repo` fixture (and some other general modernization)
The test runtime is significantly reduced (~50%). I expected an improvement, but the extent is surprising. The new `init` codepath spawns fewer subshells, and GitPython was always slow in our benchmarks.
Locally:
- without coverage: 73 sec -> 38 sec (48% drop)
- with coverage: 120 sec -> 50 sec (59% drop)
On CI:
- `3.9`: 246 sec -> 110 sec (55% drop)
- `3.10`: 252 sec -> 123 sec (51% drop)
- `3.11`: …
=> NF/TST: add `repo(init=bool)`, and assorted test modernization

.github/workflows/deploy_demo.yaml, .github/workflows/tests.yaml
This adds a workflow to run after the tests on `main` to generate the demo repository and force push it to `psyinfra/onyo-demo`.
It uses a fine-grained personal access token associated with my account. Unfortunately, it is limited to 1 year, so it will need to be updated. It is added to the "environment" for the `onyo` repository.
I considered adding a worflow directly to the `onyo-demo` repository, and trigger it from the `onyo` repo workflow. The goal of this was to avoid the need for an access token for the push, but the trigger still requires an access token, so it didn't solve anything.
=> DEMO: generate and deploy demo

README.md, demo/generate_demo_repo.sh, onyo/commands/edit.py, onyo/commands/new.py, onyo/commands/set.py, onyo/commands/unset.py, tests/demo/reference_git_log.txt, tests/demo/test_generate_demo_repo.py
The main changes in this PR are:
- add the onyo demo repo to the tests (#263)
- make commit message content reproducible (#274)
For the commit messages, I considered changing `Repo.files_staged` to a list. However, other properties would also need to be updated, to maintain consistency.
Furthermore, I felt that a list would arguably be misleading, as the order returned by `git` is merely alphabetized, rather the order in which files were staged.
Thus, I decided to keep the properties as `set`s, and make the change where it's needed: the commit message.
=> TST/BF: add demo repo generation to the test suite

onyo/commands/edit.py, onyo/commands/history.py, onyo/commands/tree.py, onyo/lib/onyo.py
This PR fixes two bugs, both connected to certain special characters.
- Parsing of `git ls-files` output contains quotes if files have some special characters:
- Use `git ls-files -z` to get list of files in `Repo._get_files()` without additional quotes
- Update parsing of this list accordingly
- close #277 
- `os.system` parses paths with spaces, quotes etc. differently then `subprocess.run`
- replace `os.system` with `subprocess.run` for `onyo tree`
- use `shlex.quote()` for giving paths as input to `os.system`
=> BF: allow special characters

onyo/lib/onyo.py, tests/commands/test_new.py, tests/lib/test_Repo_new.py
This PR:
- moves `onyo new` tests under `tests/commands`
- adds tests for `Repo.valid_name()`
- refactors `Repo.valid_name()` to simplify it and accept both `str` and `Path`
=> RF: `Repo.valid_name()`

tests/commands/test_mkdir.py, tests/commands/test_new.py, tests/commands/test_set.py, tests/commands/test_unset.py
This modernizes the tests for `onyo mkdir` and `onyo new`.
Since `test_mkdir.py` was fairly old, I now introduce fixtures, doc-strings and other modernizations to it.
I use in `test_new.py` now `@pytest.mark.repo_dirs(*directories)`, instead of listing all directories to be used in the test case separately.
The PR #278 did introduce a BF that stops onyo from breaking when special characters are used in asset or directory names, so that `onyo mkdir` and `onyo new` now both have additional tests for special characters.
=> TST: modernize `test_new.py` and `test_mkdir.py` and add special character test cases to them

tests/commands/test_config.py, tests/commands/test_init.py, tests/commands/test_mv.py, tests/commands/test_onyo.py, tests/commands/test_rm.py, tests/conftest.py
This PR modernizes the last portions of the test suite to allow dropping `populate_repo`, `clean_sandboxes()` and `change_cwd_to_sandbox()`.
It also removes redundant test functions from the `test/commands` dir that are already covered by the tests in `test/lib`.
This PR closes #251, #252, #253
=> TST: Modernize remaining old-style tests

onyo/commands/shell_completion.py
This PR includes two fixes:
1) remove both forms of a flag from the suggestion list after its been used (previously, only the form used was removed)
2) prevents shell-completion from exploding with non-int nargs to flags
The fix for 2 is imperfect, but it gets the tests passing again for #282 and #290 
I have added a lengthy comment to the fix for 2. The proper solution is unclear to me, and may require posting to the ZSH mailing list.
Until then, users for query-style commands should do one of the following:
* use `--paths` before `--keys` (which has no idea of completion
* or use another flag (such as `--yes`) after `--paths`, which will then return to normal behavior
=> BF: shell-completion fixes

demo/generate_demo_repo.sh, onyo/lib/onyo.py, onyo/main.py, tests/commands/test_set.py, tests/commands/test_unset.py, tests/demo/reference_git_log.txt
This probably still breaks, since the demo needs to be updated.
The main changes introduced in this PR:
- new syntax for set/unset in `main.py` like discussed in #286 
- this is not closed, since it still needs to happen with the implementation of `onyo get`
- updates tests for set/unset with new syntax
- updates `repo.py` for the new parsing (no splitting at comma anymore)
Close #116
=> CLI: use new syntax from #286 for set/unset

onyo/commands/edit.py, onyo/commands/mkdir.py, onyo/commands/mv.py, onyo/commands/new.py, onyo/commands/rm.py, onyo/commands/set.py, onyo/commands/unset.py, onyo/lib/onyo.py, onyo/main.py, tests/commands/test_edit.py, tests/commands/test_mkdir.py, tests/commands/test_mv.py, tests/commands/test_new.py, tests/commands/test_rm.py, tests/commands/test_set.py, tests/commands/test_unset.py, tests/demo/reference_git_log.txt
This adds flags (`-m` a.k.a. `--message` for all commands, and `--yes` and `--quiet` edit) and tests for the new flags.
The PR also normalizes the default commit messages (like discussed in #295) with the new function `Repo.generate_commit_message()` that automatically builds (and shortens, if needed) commit messages.
While I touched the older tests, I modernized them slightly. These changes are not meant to be a complete overhaul or something like it, but really just uplift them so they are easier to modify in the future (e.g. I removed a lot of hardcoded variables and asset names, and I added parametrization and `pytest.mark.repo_files(*assets)` instead).
Changes:
- adds `--message` flag to all commands except `onyo init` and `onyo config` (close #90)
- changes are made in `main.py` and …
=> NF: Add flags, change commit messages, update tests

demo/generate_demo_repo.sh, onyo/commands/mkdir.py, onyo/commands/mv.py, onyo/commands/rm.py, onyo/main.py, tests/commands/test_mkdir.py, tests/commands/test_mv.py, tests/commands/test_onyo.py, tests/commands/test_rm.py, tests/lib/test_Repo.py
**Changes:**
This adds the flags `--yes` and `--quiet` to `onyo mkdir`, and uses the same function for the "user response" for the commands `mkdir`, `mv` and `rm` that is already used in the commands `edit`, `new`, `set` and `unset`.
Thereby, all committing commands (except init and config) response now in a more unified way.
The PR updates tests (including output), and the demo were `onyo mkdir --yes` is used, and adds new tests for the added flags and user responses.
**FYI:**
The `user_response()` will create a need to update the commands later, when we move the interactive functions to another place, and yet I still think this PR will prepare the move, since just the import line has to be changed later, not the code of the `mkdir()` function itself.
I removed some unneeded tests (e.g. …
=> Normalize "user response" for all commands ; add flags `--yes` and `--quiet` to `onyo mkdir`

setup.py, tests/commands/test_init.py
To ensure we don't accidentally introduce inter-test dependencies.
=> TST: run tests in random order

pytest.ini, tests/commands/test_unset.py, tests/conftest.py
I added the `repo_contents` fixture, and to demonstrate the usage and functionality, I updated `test_unset.py` with it.
Also, I reduced some of the redundant/overlapping tests (i.e. the test directory names do not need multiple dirs with spaces), like I already did for many of the other tests.
=> TST: add  `repo_contents` fixture to set values in assets; use fixture for `test_unset.py`

onyo/commands/cat.py, onyo/commands/config.py, onyo/commands/fsck.py, onyo/commands/history.py, onyo/commands/mkdir.py, onyo/commands/shell_completion.py
I hate this everytime I see it. I added just pyre and lines to fix pyre when it errored then, e.g. `repo = None`.
=> Add: Pyre in all commands!

onyo/commands/tree.py, tests/commands/test_tree.py
`onyo tree PATH` did test that the opdir is in the repository, but did not test if the PATH given as input is in the repository, which I fixed.
To verify that the fix does not introduce new bugs, I added `test_tree.py`, because it seems we never had any tests at all for this command.
Close #121
=> BF/TST: check PATH is in repo for `onyo tree PATH`; add `test_tree.py`

onyo/lib/onyo.py
No need for the variable was identified.
close #314
=> onyo.py: remove unneeded variable `Repo._gitfiles`

tests/commands/test_cat.py, tests/commands/test_config.py, tests/commands/test_edit.py, tests/commands/test_history.py, tests/commands/test_init.py, tests/commands/test_onyo.py, tests/commands/test_rm.py
This PR contains a lot of small modernizations, that basically try to make all tests look/work similar, which mainly add or effect Pyre, doc-strings, parameterization, usage of the new fixture, and such things, that I found while looking through the tests for the commands. These do not add any functionality as such, but rather are meant to make the tests easier to update in the future. Also, I used valid asset names in tests (except for cases that do not test the behavior for invalid names, obviously).
Also, in some cases I noticed some of our more classic test cases missing, e.g. deletion of directories with `onyo rm`, or having at least one or two test cases for each flag of the commands. This is not meant to cover all scenarios in this PR, but I think it will help in case we want to …
=> TST: Modernize/streamline the tests for commands

onyo/commands/cat.py, onyo/commands/config.py, onyo/commands/edit.py, onyo/commands/fsck.py, onyo/commands/history.py, onyo/commands/init.py, onyo/commands/mkdir.py, onyo/commands/mv.py, onyo/commands/new.py, onyo/commands/rm.py, onyo/commands/set.py, onyo/commands/shell_completion.py, onyo/commands/tree.py, onyo/commands/unset.py, onyo/main.py
Adds typing `argparse.Namespace` to all commands.
Adds typing to some functions in `main.py`.
Changes default values in argparsing in `main.py` to have consistent types (i.e. lists of `Path`).
Close #319
=> Consistency: add typing to commands; update default values and add some typing in main.py

onyo/lib/onyo.py
The function to re-set the caches to `None` do exist since the implementation of `onyo set`, yet they were not used in most functions, and neither in a consistent way.
This commit adds a `clear_caches()` call to the end of all functions in the API that modify the caches, and to the command `onyo new` in the function modifying the state of the repository, e.g. adding new assets.
While doing these changes, I noticed how much we should have something like API-workflow tests, or like the demo, since it is quite hard to verify that not some other functions (e.g. `restore()`, `add()` and `commit()` as git functions) also would need a clearing of caches. I think these should not require this currently, because they get mainly called by the command-functions, or in the command-files, but we …
=> NF/BF: clear caches after modifying repository

README.md
This should briefly explain the conventions to follow for contributions of the Onyo project, including the code base under lib and what should be tested for, for outside contributers, but also us, currently and especially in the future.
I chose to re-organize part of the existing readme, and then add under "Develop" (which did not have contents so far) the conventions I assume to be fitting for onyo.
=> README: add section "Code Conventions"

onyo/commands/set.py, onyo/commands/unset.py, onyo/lib/onyo.py, onyo/main.py, tests/commands/test_set.py, tests/commands/test_unset.py
Change the argparse defaults for the `--depth` flag in `onyo set` and `onyo unset` to 0, and have 0 mean "no depth limit". Rather than have onyo crawl through the directory structure of the repository, it will instead filter `self.assets` based on path and depth requirements. Tests have been modified to work with the new "0 is no depth limit" setting.
There are a few things that still require discussion:
1. `depth` as a positive integer should be a type annotation, rather than an error in `_set_sanitize`
2. In argparse, one could use `cmd_set.add_argument('--depth', type=positive_int)`, writing a `def positive_int(value)` that returns `int(value)` if the value is positive, otherwise returning an `argparse.ArgumentTypeError`, therefore disallowing negative values. At the least the type …
=> Change depth=0 to a no-limit depth and add it as default

tests/__init__.py
The `__init__.py` is needed to make functions and variables inside of the project explicitely import-able, otherwise the CI errors with a `ModuleNotFoundError`.
=> BF: add `tests/__init__.py` to enable importing from conftest

onyo/commands/mkdir.py, onyo/commands/tree.py, onyo/lib/onyo.py
This PR addresses the use of `Repo._n_join`, replacing it with `'\n'.join(map(str, to_join))`. I've also addressed some other string formatting issues for methods I've touched with this change. There are more string formatting issues to address throughout the codebase, but addressing those here would make the PR very large.
There is one commit on refactoring `Repo._fsck_unique_assets()`, which was done to both make the code more readable, but also make the subsequent error logging more straightforward.
=> Remove Repo._n_join and refactor its use

onyo/commands/cat.py, onyo/commands/config.py, onyo/commands/edit.py, onyo/commands/fsck.py, onyo/commands/get.py, onyo/commands/history.py, onyo/commands/mkdir.py, onyo/commands/mv.py, onyo/commands/new.py, onyo/commands/rm.py, onyo/commands/set.py, onyo/commands/tree.py, onyo/commands/unset.py, onyo/lib/onyo.py, tests/lib/test_Repo.py
To remove ambiguity in situations were a `Repo` object is instantiated with a path that is a subdirectory inside a repository, and a function of `Repo` is called with a relative path, this PR updates the `Repo` class so as to only accept the root of an onyo repository.
- Updates `Repo` to either just allow root as path to instantiate, or to use `Repo(find_root=True)` to search the root from a subdirectory inside a repo
- Adds `Repo._find_root()` to allow the easy identification of the root of an existing repository when called from a subdirectory of it
- Applies changes to commands
- Updates existing `tests/lib/test_Repo.py` to be conform with new behavior
- Adds tests for `Repo._find_root()`
This is the first step in the direction of working only with absolute paths in Repo, and to …
=> `Repo` must be instantiated with root

onyo/commands/edit.py, onyo/commands/get.py, onyo/lib/onyo.py, onyo/lib/utils.py, tests/commands/test_get.py, tests/commands/test_new.py, tests/commands/test_set.py, tests/commands/test_unset.py, tests/lib/test_Repo.py, tests/lib/test_Repo_add.py, tests/lib/test_generate_commit_message.py
Changes added:
- all properties are now absolute paths
- all `git` queries (e.g. `git ls-files`) are run from `repo.root` to contain all assets/dirs etc from the repo, not just relative to `repo.opdir`, and all are absolute
- adds functions:
- `Repo.sanitize_path()`: checks if paths are absolute or relative to the opdir and returns them as an absolute `Path`
- `Repo.relative_to_root()`: returns for a set of absolute paths (that must be inside of the repository) a set of Pathsrelative to `repo.root`
- `relative_to_opdir()`: returns for a set of absolute paths as set of Paths relative to the operating directory
- updates the generating of commit messages to still display paths relative from `repo.root`
- updates the tests/commands which are effected by the changes to work with the changes …
=> (RFC) lib: properties/paths are absolute, git requests are made from repo.root

onyo/commands/cat.py, onyo/commands/config.py, onyo/commands/edit.py, onyo/commands/fsck.py, onyo/commands/get.py, onyo/commands/history.py, onyo/commands/init.py, onyo/commands/mkdir.py, onyo/commands/mv.py, onyo/commands/new.py, onyo/commands/rm.py, onyo/commands/set.py, onyo/commands/shell_completion.py, onyo/commands/tree.py, onyo/commands/unset.py, onyo/lib/command_utils.py, onyo/lib/onyo.py, onyo/lib/utils.py, onyo/main.py, tests/commands/test_edit.py, tests/lib/test_Repo.py, tests/lib/test_generate_commit_message.py
This is the next step for the efforts of simplifying path handling in onyo and commands, while removing bugs and addings tests for those changes.
- change cwd to `opdir` in `main.py`
- `opdir` is exclusively used in `main.py`  (relevant if `onyo -C <path>` is called)
- retire `repo.opdir` and `opdir` in lib, commands and tests
- remove `repo.sanitize_path()`
- `Path(<path>).resolve()` is now used in commands, since `repo.sanitize_path()` did nothing else after retirement of `opdir` anyways
=> Pathing: retire `repo.opdir` and `repo.sanitize_path()`

onyo/tests/test_usecases.py
Addressing the first part of #345, this patch implements a CLI workflow outlined in issue #345.
There are not a lot of assertions in this test yet. There's little use in repeating assertions from the command tests. This is supposed to:
- test that desired operations are actually expressible with onyo's interface (not the currently the case for querying assets for a value within a given range and for limiting the matches to exclude certain subtrees)
- test that an entire flow doesn't encounter barriers that are unaccounted for in isolated tests for single commands
- test that and how information retrieved by one command can be used in the next
- inform further refinement of interfaces, features and outcome definitions
Additional assertions should come from decisions made (documented in …
=> Implement usecase tests

docs/source/cmd_get.rst, docs/source/cmd_unset.rst, docs/source/command_line_reference.rst, onyo/commands/get.py
Build of docs with the changes of this PR:
https://onyo--364.org.readthedocs.build/en/364/
Everybody of us knows that the docs are not up to date.
Everybody of the developers wants to have a place to look up how Onyo commands *should* behave.
Everybody who uses Onyo wants to know what commands do.
- I added the missing parts for `onyo get`/`onyo unset` to the docs, so that these get auto-generated pages, too
- I updated the description of `onyo get` with information from issue #18
Currently this does not add new information, I will begin the work through the documentation and ambitously hope that in the end we have a reference for all commands, that everybody agreees with.
=> Docs: Overhaul "Command Line Reference"

onyo/commands/tests/test_mkdir.py, onyo/lib/onyo.py
Previously checking path parts for being '.anchor' was reduced to only check for files, since technically only such files are relevant. However, allowing directories being named '.anchor' would take up the space of the '.anchor' file of its parent. Hence, one could only ever do that in a repo that wouldn't currently pass validation and one would end up making it harder to fix. So, go back to not allow for this.
=> BF: Disallow dirs named .anchor

onyo/lib/git.py
`GitRepo._git` uses `self.root` by default now. Furthermore, it makes little sense to call git from elsewhere in a method that is bound to a concrete repository. Hence, the only currently valid use of the `cwd` argument is the git-init call.
Remove all other usages of `cwd` as well as `-C ...` in the command call.
Closes #348
=> Remove superfluous CWD specification for git calls

onyo/lib/command_utils.py, onyo/lib/commands.py, onyo/lib/git.py
Further consolidation of separating abstraction layers by moving uses of the git-call wrapper `GitRepo._git` into dedicated `GitRepo` methods.
=> RF: Move direct git calls

onyo/commands/tests/test_mkdir.py, onyo/lib/commands.py, onyo/lib/onyo.py
- Closes #371 (`onyo mkdir` now behaves like `mkdir -p` with respect to existing directories)
- Replace remaining, hardcoded `.anchor` strings by the central definition `OnyoRepo.ANCHOR_FILE`.
=> Fix for mkdir + minor clean up

docs/source/concepts.rst, docs/source/configuration.rst, docs/source/examples.rst
This commit is not about adding new examples or use-cases, I just correct existing information which was out of date:
- `onyo new` does not read fields interactive/separately, but expects a full asset-path
- apply new syntax (e.g. new syntax for flags `--keys` and `--path`) to the commands `onyo new` and `onyo set`
- we new expect assets that expect the name-scheme to be correct, so I renamed the incorrect `laptop_lenovo_T490s` (without serial) to the correct `laptop_lenovo_T490s.abc123`
- the example template is changed to `.onyo/templates/empty` and actually an empty file, instead of the old name `standard`, which did contain `---`
=> docs: correct/update existing information

onyo/commands/tests/test_set.py, onyo/lib/assets.py, onyo/lib/command_utils.py, onyo/lib/commands.py, onyo/lib/git.py
This one more step working towards #370, #377, #383, and a consolidation of `assets.py` as pointed to in #386 under 4.
For the latter, follow up PRs on `unset` and `get` are necessary as well.
- Restructures the implementation of `set` mainly targeting #370
- Introduces usage of `difflib` in order to not do modifications on disc before asking the user for confirmation.
- By extension this is also addressing #377, because now a dryrun does not actually write anything
- Minor adjustment to git usage: Don't call `restore` twice for moves, but pass both paths instead.
=> Restructure `set`

onyo/commands/set.py, onyo/commands/unset.py, onyo/lib/assets.py, onyo/lib/commands.py, onyo/main.py
This PR just copies the stuff from `onyo get` to the commands unset and set, too.
Close https://github.com/psyinfra/onyo/issues/113
Close https://github.com/psyinfra/onyo/issues/285
TODO: Tests are still missing.
The function used by onyo get to filter seems to me to be quite badly written, which leads to a few awkward things I had to do. IMO the function should be split up into two parts, the first doing what https://github.com/psyinfra/onyo/issues/259 describes, and a separate one should do the filtering by keys, which is just needed by onyo get.
=> set/unset: add flag `--filter`

onyo/lib/assets.py, onyo/lib/command_utils.py, onyo/lib/commands.py
This is a follow up on #382, addressing #370, #377, and #383 for `unset`, which now does not stage modifications in order to roll them back, but only writes to disc if actually needed. Like `set` before via #382, it uses difflib instead of `git-diff` in order to show to-be-applied changes.
=> Fix up unset

docs/source/configuration.rst, onyo/commands/cat.py, onyo/commands/config.py, onyo/commands/edit.py, onyo/commands/fsck.py, onyo/commands/get.py, onyo/commands/history.py, onyo/commands/init.py, onyo/commands/mkdir.py, onyo/commands/mv.py, onyo/commands/new.py, onyo/commands/rm.py, onyo/commands/set.py, onyo/commands/tree.py, onyo/commands/unset.py, onyo/lib/command_utils.py, onyo/lib/commands.py, onyo/main.py
We have multiple places in the python code that are used to auto-generate our onyo docs: https://onyo.readthedocs.io/en/latest/index.html
The changes of this PR focus on updating these texts to have better onyo docs; this PR does not contain the discussed move of arg-parser code into the commands (I was unable to do this, and after some hours I decided to focus on the texts for now).
Some of my changes correct text, others remove incorrect (or unneeded) information, sometimes I add something, or I just normalize information, so that we use the same terms along commands.
The relevant main changes of this PR:
- change texts in (sub-)command flags and arguments
- change docstrings in command-functions used to autogenerate docs
- normalize empty/None default values in argparser (works toward …
=> docs: change texts for arguments in argparser and doc-strings of commands

demo/generate_demo_repo.sh
Before, we used a rather complicated example with wildcards to demonstrate how to set a value for all laptop assets.
Now, I updated the demo to use `--filter` instead, because since #353 `onyo set` has that functionality.
Close #266
=> demo: use `onyo set --filter`

onyo/commands/cat.py, onyo/commands/config.py, onyo/commands/edit.py, onyo/commands/get.py, onyo/commands/history.py, onyo/commands/init.py, onyo/commands/mkdir.py, onyo/commands/mv.py, onyo/commands/new.py, onyo/commands/rm.py, onyo/commands/set.py, onyo/commands/shell_completion.py, onyo/commands/tree.py, onyo/commands/unset.py, onyo/main.py, onyo/shared_arguments.py
Done:
- Moves the command-definitions into the commands, and import those in `main.py` for the argparser.
- Adds 'shared_arguments.py', that defines types for shell-completion and contained shared arguments:
`--yes`, `--quiet`, `--dry-run`, `--filter`, `--message`, `--depth`
There might be some flags that possibly could be more generic and moved to shared arguments, but these do currently differ in aspect of `nargs=?/*`, there helptext, or like `keys` that is sometimes just a list, and other times a key value pairs list.
This PR focusses on moving the arguments to `shared_arguments.py` that are already good to go because they work in an identical manner, and do not break any existing tests.
=> main/commands: move args-definition into commands; import them in main.py

demo/generate_demo_repo.sh, onyo/__init__.py, onyo/argparse_helpers.py, onyo/commands/cat.py, onyo/commands/config.py, onyo/commands/edit.py, onyo/commands/get.py, onyo/commands/history.py, onyo/commands/init.py, onyo/commands/mkdir.py, onyo/commands/mv.py, onyo/commands/new.py, onyo/commands/rm.py, onyo/commands/set.py, onyo/commands/shell_completion.py, onyo/commands/tests/test_edit.py, onyo/commands/tests/test_mkdir.py, onyo/commands/tests/test_mv.py, onyo/commands/tests/test_new.py, onyo/commands/tests/test_onyo.py, onyo/commands/tests/test_rm.py, onyo/commands/tests/test_set.py, onyo/commands/tests/test_unset.py, onyo/commands/tree.py, onyo/commands/unset.py, onyo/main.py, onyo/onyo_arguments.py, onyo/shared_arguments.py, onyo/tests/test_usecases.py
This continues the efforts to define the arguments in dedicated locations (either in the commands itself, in shared_arguments.py or in the newonyo_arguments.py) instead of in main.py; main.py just reads the other locations and creates the parsers for arguments generically.
The main changes are:
1. every command has just one argument dictionary which can be read in main.py
2. shared_arguments get imported in commando-scripts and removed from main.py
3. onyo_args are moved/defined in a seperate file, this includes:
- yes and quiet are now onyo flags, not command flags
- --version, -C, and --debug are also there
4. corrects tests, removes old code, etc
=> onyo: define arguments in dedicated locations, read them generically in main.py

onyo/lib/git.py, onyo/lib/onyo.py, onyo/lib/tests/test_git.py
This PR adds tests and docstrings for the `GitRepo` class, in parallel to the changes for `OnyoRepo` during #394.
Changes:
- adds tests to some functions of `GitRepo`
- adds or normalizes docstrings (based on discussion in #339)
=> TST/DOC: add tests and use new docstring style for class `GitRepo`

onyo/__init__.py, onyo/commands/cat.py, onyo/commands/config.py, onyo/commands/edit.py, onyo/commands/get.py, onyo/commands/history.py, onyo/commands/mkdir.py, onyo/commands/mv.py, onyo/commands/new.py, onyo/commands/rm.py, onyo/commands/set.py, onyo/commands/shell_completion.py, onyo/commands/tree.py, onyo/commands/unset.py, onyo/lib/__init__.py, onyo/lib/assets.py, onyo/lib/command_utils.py, onyo/lib/commands.py, onyo/lib/filters.py, onyo/lib/onyo.py, onyo/lib/tests/test_onyo.py, onyo/lib/ui.py, onyo/main.py
This PR will close #255
Main changes:
- The UI object is once created
- parameters (e.g. `--yes`, `--quiet`, `--debug`) are set in `main.py`
- all other parts of Onyo import the ui object (except if it would cause circular imports)
- all printing, logging, erroring, and other user interactions are handled with this object
TODOs:
- `onyo get` is implemented quite differently to the rest; still need to unify for UI:
- rich
- machine_readable
- sort ascending/descending
- interactive
- unify `interactive`/`non-interactive` for all commands
- should everything, including assets.py use the new form ui-logging? This leads to Circular imports
- add tests
=> UI: add `ui.py` and use it to replace prints, logs, etc

.github/workflows/tests.yaml, README.md, docs/source/installation.rst, onyo/lib/git.py, setup.py
And add `3.12` to the test matrix.
=> TST/DOC: bump Python baseline 3.9 -> 3.11

onyo/commands/tests/test_edit.py, onyo/commands/tests/test_init.py, onyo/commands/tests/test_mkdir.py, onyo/conftest.py, onyo/lib/git.py, onyo/lib/onyo.py
This addresses an issue identified in #349
The issue specifically identifies an anti-pattern in the tests of wrapping a `path` object with `Path()` when concatenating.
The majority of changes in this PR are indeed that, but I did not limit myself to the tests, nor just that particular unnecessary use of `Path()`. I made others simplifications when I encountered them.
I did not go through all invocations of `Path()` exhaustively, as that would be an extraordinary amount of effort. However, `git grep 'Path(' | grep ','` is now clean of this pattern, and I can say that likely the majority of these have been fixed.
=> TST/BF: remove unneccesary `Path` invocations

onyo/argparse_helpers.py
Simply raising from with a custom Action's  doesn't do. Instead properly detect invalid values and issue an error with the parser.
Closes #410
=> Fail correctly in argparse Action

demo/generate_demo_repo.sh, onyo/lib/commands.py, onyo/lib/inventory.py, onyo/lib/onyo.py, onyo/lib/tests/test_onyo.py, onyo/tests/demo/reference_git_log.txt
The demo repository did not work anymore because of the new syntax, this PR fixes it.
Includes the newly merged changes regarding less whitespace/indentation in run-records.
This PR updates:
- the shell script generating the demo repository to the new syntax
- The git reference log to run the demo-test successfully
- the code in commands.py that generated was different for each command; this replaces the code and uses instead the function `generate_commit_message()` everywhere
- the code in `generate_commit_message()` was reduced. Before, it did generate (when `-m` was not used) a commit message subject and body. This was lately replaced with the run-records, so the commit message body generation could be completely removed from the function
=> BF: Repair demo repository generation

onyo/commands/tests/test_cat.py, onyo/commands/tests/test_get.py, onyo/commands/tests/test_unset.py, onyo/lib/commands.py, onyo/lib/executors.py, onyo/lib/inventory.py, onyo/lib/tests/test_inventory_operations.py
This patch: 
- fixes `onyo cat` for the case of invalid assets files. New behavior is: Issue an error message, still print the content and return non-zero.
- fixes `onyo rm` for the case of removing a non-empty directory
- skips the tests for `unset` and `get` , since they are not currently expected to work
Should bring the number failures down to 87, 82(?) of which are actually the same issue in `set`.
=> Towards re-establishing CI baseline

onyo/lib/command_utils.py, onyo/lib/commands.py, onyo/lib/consts.py, onyo/lib/inventory.py, onyo/lib/onyo.py, onyo/lib/utils.py
While using sets is obviously fine in some places, don't use it for the sole purpose of deduplicating a list, since this is loosing order.
In addition introduces `lib/consts.py` to hold constants. Added to this PR to avoid circular imports.
Closes #440
Closes #318
=> Don't deduplicate lists by casting as set

onyo/commands/tests/test_edit.py, onyo/commands/tests/test_set.py, onyo/lib/commands.py, onyo/lib/exceptions.py, onyo/lib/inventory.py
This patch lets commands uniformly check the `Inventory` for pending
operations before trying to display a diff and asking for confirmation,
avoiding pointless empty lines and "questions about nothing".
`Inventory.modify_asset`, `Inventory.rename_asset` and
`Inventory.rename_directory` can potentially raise a `NoopError`,
allowing the caller to decide whether this should lead to failure or not
(following a result-oriented approach where a call to these methods is
not looked at as "do this" but as "make sure this the state afterwards").
This was partially implemented before, but not yet uniformly.
This should reduce current test failures to 3 (my local result - to be confirmed by CI)
=> Iron out behavior when commands have nothing to do

onyo/commands/set.py, onyo/commands/tests/test_set.py, onyo/lib/commands.py, onyo/lib/inventory.py
Removes now superfluous dryrun option for `set`. Note, that dryun still exists for `unset`, because that command still needs a rewrite anyway.
=> `set`: remove dry-run

onyo/conftest.py, onyo/lib/tests/test_commands_mv.py, onyo/lib/tests/test_commands_new.py, pytest.ini
This provides a fixture setting up `onyo.lib.ui`, that is run for every
test. Settings for `yes`, `quiet` and `debug` are read from a new test
marker 'ui' if given. Otherwise set to defaults (`False` for all of
them). The marker takes a dictionary, allowing to enhance this later on
for other future features of the `UI` object (like using the rich
package or redirecting logging or whatever else).
Note, that this is not going to work for CLI tests, since they spawn a
subprocess with its own python context. However, that is obviously
fine, since the CLI calls take explicit flags for that.
=> Fix interactive testing

onyo/commands/tests/test_new.py, onyo/commands/tests/test_set.py, onyo/lib/commands.py, onyo/tests/test_usecases.py
Fixes remaining failures due to new interfacee of  `onyo new` and turns remaining cases of `raise RuntimeError("TODO: ...` into `pytest.skip("TODO...`. This should re-establish a "green" CI pipeline (provided #468 merged), so we can stop the hackathon related phase of merging things that don't pass.
=> Fix test failures

onyo/argparse_helpers.py, onyo/commands/tests/test_get.py, onyo/conftest.py, onyo/lib/assets.py, onyo/lib/command_utils.py, onyo/lib/commands.py, onyo/lib/differs.py, onyo/lib/git.py, onyo/lib/inventory.py, onyo/lib/onyo.py, onyo/lib/recorders.py, onyo/lib/ui.py, onyo/main.py
This is purely a syntax uplift thing that just took me a few minutes. If it's not desired, I'm happy to walk away from it.
Now that the Python baseline is 3.11, we can use the new, more terse syntax introduced in Python 3.10.
- https://docs.python.org/3/library/stdtypes.html#types-union
- https://docs.python.org/3/library/typing.html#typing.Optional
The one controversial thing I see is the use of `Optional` (which some feel is poorly named) in place of `something | None`. This can feel odd when defining what a function returns:
```
def yope(Optional[str]) -> Optional[int]
...
```
If people bump on that, we can simply avoid `Optional`.
=> BF: replace Union with new `|`-syntax and `Optional[]`

docs/source/cmd_unset.rst, onyo/commands/tests/test_unset.py, onyo/commands/unset.py, onyo/lib/commands.py, onyo/lib/git.py, onyo/main.py, onyo/shared_arguments.py
Removes `--dry-run` everywhere, including commands, main/shared_arguments, tests and docs.
The flag is out of date and mostly removed anyways -- this PR just removes the last references to it.
=> onyo: remove dry-run

onyo/commands/cat.py, onyo/commands/config.py, onyo/commands/edit.py, onyo/commands/get.py, onyo/commands/rm.py, onyo/commands/tree.py, onyo/lib/commands.py, onyo/lib/git.py, onyo/lib/onyo.py
In commands:
- changes in command functions the type from `OnyoRepository` ->`Inventory` (#467) 
- to make the API more intutive, we pass now always the same variable type (except for unset and fsck, which need to be refactored still)
- updates variable names and types/typehints in command functions in `commands.py`
This PR also adds keyword "optional" to doc-strings to follow numpydocs.
Close #467
Close #341
=> commands: normalize parameter types and names, normalize docstrings 

onyo/lib/commands.py, onyo/lib/onyo.py, onyo/lib/tests/test_onyo.py, onyo/tests/demo/reference_git_log.txt
The function `generate_commit_message()` now gets a format string defining the commit message subject to be generated, so that this function just has the job of shortening given paths and insert them into the format_string.
The function `generate_commit_message()` (before this were still two functions, together with `_generate_commit_message_subject()`) contained a lot of dead code, e.g. references to modified paths of git.
Also, the function did a bunch of other things before (e.g. command specific work like adding the keys updated with `onyo set` if set was used) other than shortening paths. These are now done before calling it, and just inserted into the format_string.
Close #462
=> generate_commit_message: remove old code, update usage

onyo/commands/set.py, onyo/commands/tests/test_edit.py, onyo/commands/tests/test_new.py, onyo/commands/tests/test_set.py, onyo/conftest.py, onyo/lib/assets.py, onyo/lib/command_utils.py, onyo/lib/commands.py, onyo/lib/differs.py, onyo/lib/filters.py, onyo/lib/inventory.py, onyo/lib/onyo.py, onyo/lib/tests/test_Filter.py, onyo/lib/tests/test_commands_new.py, onyo/lib/tests/test_inventory_operations.py, onyo/lib/utils.py
This is primarily addressing the order and places in which the generation of values in assets (like 'faux' serials and its actual name) and the validation of the resulting assets is happening.
For more details please check the commit messages.
Closes #457
Closes #455
Closes #443
Closes #437
Closes #435
Closes #424
Closes #417
Closes #413
Closes #412
Closes #411
=> Fix order of asset validation/evaluation

onyo/lib/differs.py, onyo/lib/executors.py, onyo/lib/recorders.py
Inventory operation records used wrong target path when a rename
operation was recorded. The basename of the target was repeated,
indicating a directory with the same name containing the target.
Reason was that the respective recorders used the same helper function
as move recorders. The latter did, however, expect the dir to move into
as argument.
Fixed by providing a dedicated helper for rename records.
Also fixed another bug, where only the basename was treated as target
path when renaming a directory. This behavior was changed for assets
already, but directories were missing that fix.
Closes #414
=> BF: Fix rename operation records 

onyo/lib/commands.py, onyo/lib/inventory.py, onyo/lib/tests/test_inventory_operations.py
Asset validation for new_assets and modify_assets operations now fail,
when a required key has an empty value.
Closes #481
=> Enforce non-empty values for required keys

onyo/lib/inventory.py, onyo/lib/tests/test_commands_mv.py
Moving/renaming assets/directories did not always check for the target to exist and could silently overwrite.
Won't address coverage herein. That's part of #487.
Closes #459
=> BF: `mv` overwrote target

onyo/commands/tests/test_mv.py, onyo/lib/commands.py
close #420
close #421
The command did fail (which is the correct behavior), but printed the wrong error messages.
=> BF: print correct error when calling mv to non-existing destination directory

onyo/commands/tests/test_edit.py, onyo/commands/tests/test_history.py, onyo/conftest.py, onyo/lib/assets.py, onyo/lib/command_utils.py, onyo/lib/commands.py, onyo/lib/executors.py, onyo/lib/git.py, onyo/lib/inventory.py, onyo/lib/onyo.py, onyo/lib/tests/test_commands_mv.py, onyo/lib/tests/test_commands_new.py, onyo/lib/tests/test_git.py, onyo/lib/tests/test_inventory_operations.py, onyo/lib/tests/test_onyo.py, pytest.ini
This is largely focusing on ironing out the base layer(s) in `GitRepo` and `OnyoRepo`.
- For almost everything, only the committed state of the repository is considered, making most functionality rely on `git ls-files` via the `GitRepo.files` property and the `GitRepo.get_subtrees` method.
- The above involves a clean up of caching. With this patch, only `GitRepo.files` and `OnyoRepo.asset_paths` are cached and the only place to invalidate the cache is consequently the respective `commit` method.
- Introduces new `gitrepo` and `onyorepo` fixtures that are taking a step towards more generic tests, that query the object they get to formulate assertions rather than hardcoding assumptions about it. This should lead to significantly reducing the effort of future adjustments to these tests.
- …
=> Rework `GitRepo` and `OnyoRepo`

onyo/commands/tests/test_mv.py, onyo/lib/tests/test_commands_mv.py
This adds tests for `commands.onyo_mv()`, and cleans up the CLI tests for `onyo mv`.
There might be some cases missing that should be tested, and during review it should be checked that I did not remove CLI tests that are wanted after all. I also did not test yet for specific commit message contents.
PS: The missing coverage is because of the temporary test for issue #516. I skip the test, because it is not yet working and we have to decide on how to handle this.
=> TST: add tests for `onyo_mv()`

onyo/commands/cat.py, onyo/commands/mv.py, onyo/commands/new.py, onyo/commands/rm.py, onyo/commands/tests/test_rm.py, onyo/commands/tree.py, onyo/lib/commands.py, onyo/lib/tests/test_commands_cat.py, onyo/lib/tests/test_commands_mkdir.py, onyo/lib/tests/test_commands_new.py, onyo/lib/tests/test_commands_rm.py, onyo/lib/tests/test_commands_set.py, onyo/lib/tests/test_commands_tree.py, onyo/lib/tests/test_onyo.py
Works towards:
- #487
- #491
- #495
- closes #522 -> here I chose as a solution to display the inventory.root if the python function `onyo_tree(inventory)` is called without paths. This needs probably feedback/discussion!
- I am not verifying the correctness of the output of `onyo_tree()`
- #493
- closes #523 -> at least one valid asset path is required by `onyo_cat()`
- #488
- closes #524 -> at least one valid directory path is required by `onyo_mkdir()`
- does not finish but works towards #490 
-  closes #526
- Updates tests and doc-strings for `onyo_new()`, but will not close the issue
- Tests for `onyo init` are contained in `onyo/lib/tests/test_onyo.py` and were updated, too
=> Docs and Tests

onyo/commands/tests/test_edit.py, onyo/conftest.py, onyo/lib/commands.py, onyo/lib/exceptions.py, onyo/lib/inventory.py, onyo/lib/tests/test_commands_mv.py, onyo/lib/tests/test_commands_rm.py, onyo/lib/tests/test_inventory_operations.py
This introduces a decorator for command implementations in order to have commands fail right away if there a running either on a dirty worktree or - in python context - on an `Inventory` object that still has pending operations.
A more command-tailored assessment of what's a valid state for a command to run on is imaginable, but we don't really have  a usecase for that so far and furthermore this introduces how to do it. We could still break theat down into several, different decorators anytime we encounter an actual need for this.
=> Command decorator for ensuring suitable inventory/repo state

onyo/commands/tests/test_config.py, onyo/commands/tests/test_set.py, onyo/lib/commands.py, onyo/lib/tests/test_commands_cat.py, onyo/lib/tests/test_commands_get.py, onyo/lib/tests/test_commands_mv.py, onyo/lib/tests/test_commands_rm.py, onyo/lib/tests/test_commands_set.py, onyo/lib/tests/test_commands_tree.py, onyo/lib/tests/test_commands_unset.py, onyo/shared_arguments.py
Changes:
1. adds/updates tests/docs for the python implementations of commands
2. at least one key to unset is required
3. `match` is now actually optional for `onyo_unset()`
4. Check for illegal `path` in keys for  `onyo_set()` and `onyo_unset()`
- close #527 
- close #528 
5. check for illegal none values in `keys`for `onyo_set()` and `onyo_unset()`
- close #530
6. Normalize default path for python functions of commands
- some (e.g. `onyo_get()` and `onyo_tree()`) already used `inventory.root` when called like `onyo_<cmd>(inventory, ...)`, while `onyo_set()` and `onyo_unset()` were still using the CWD like the command line implementations do. I normalized these and added tests for this behavior
7. correct default values and optional parameters for `onyo_get()`
- doc-strings of `get` …
=> TST/DOC: add/update tests and doc-strings

onyo/lib/ui.py
Syntax highlighting seems to be enabled by default. We don't print code, we don't want that. Brought to light by issue #542.
=> BF: Disable rich's syntax highlighting

docs/source/cmd_cat.rst, docs/source/cmd_config.rst, docs/source/cmd_edit.rst, docs/source/cmd_mkdir.rst, docs/source/cmd_mv.rst, docs/source/cmd_new.rst, docs/source/cmd_rm.rst, docs/source/concepts.rst, docs/source/configuration.rst
This PR is not meant to add anything new or to make the docs more complete; Instead it brings everything up to date, corrects the docs in regards to changes in onyo (e.g. `onyo new --path` gets a directory, not an asset name) or removes information that is simply out of date (e.g. "_" is not a reserved character anymore and can be used in keys of asset names).
This should allow other people to focus later on adding new information and help during the hackathon to either use the documentation or see that information is just not given yet, instead of wondering permanently if the user does something wrong or if the docs might just be incorrect.
=> DOCS: correct changes in syntax, remove out-of-date information

onyo/lib/commands.py, onyo/lib/inventory.py, onyo/lib/tests/test_commands_mv.py
This allows `onyo mv` to move and rename a directory in one go, but still record two separate operations.
The first two commits are a bit of a hack. Issue #546 records the need for a more generalized solution. Was aware of that problem before, but I thought it would only be relevant for more sophisticated usage of python API. Turns out, it's not ;-)
Closes #426
=> Allow mv to move + rename

onyo/commands/new.py, onyo/lib/commands.py, onyo/lib/tests/test_commands_new.py, onyo/shell_completion/zsh/_onyo
Allow to clone new asset(s) from an existing one as an ad-hoc template.
- Closes #461
@aqw: shell completion doesn't seem to work yet. I get:
```
_arguments:comparguments:327: invalid argument: (-c --clone){-c,
```
when trying to complete. Can you have a look please?
=> `new`: --clone from existing asset

onyo/shell_completion/zsh/_onyo
Standardizing on `_files` should be a no-op. It just unifies the syntax for the sake of consistency.
The misbehavior of `onyo new --path` was caught by @bpoldrack :-)
=> BF: small shell-completion fixes

onyo/lib/tests/test_commands_mkdir.py, onyo/lib/tests/test_commands_mv.py, onyo/lib/tests/test_commands_new.py, onyo/lib/tests/test_commands_rm.py, onyo/lib/tests/test_commands_set.py, onyo/lib/tests/test_commands_tree.py, onyo/lib/tests/test_commands_unset.py
This could not be tested before, because the `inventory` fixture constructed an inventory which contained un-saved files.
Since that behavior was changed, commands that might change the worktree can check it again, especially when they do some changes, or to verify that nothing was left unclean after errors where triggered.
There is no issue as such for this, instead it removes the TODOs in the code describing the necessity of this.
=> TST: check clean-ness of git worktrees for python command functions

onyo/shell_completion/zsh/_onyo
BSD "realpath" does not have the -e flag.
While not strictly necessary, I liked that it would inform the user. So I add a simple check.
fix #559
=> BF: fix tab completion for BSD systems

onyo/main.py
This allows for greatly improved readability of the help text for onyo arguments.
Actual string and formatting changes to following in a subsequent PR.
=> BF: Limit width of help text for arguments too

onyo/commands/new.py, onyo/shared_arguments.py, onyo/shell_completion/zsh/_onyo
This rewrites and reformats much of the help text for `onyo new`, and also the shared arguments.
Fixes: #395
=> BF: improve help text for `onyo new`

onyo/commands/cat.py, onyo/main.py, onyo/onyo_arguments.py, onyo/shell_completion/zsh/_onyo
This improves the help text primarily for the top-level `onyo --help` and `onyo cat --help`.
It also includes two fixes for formatting help text broadly:
- strip leading and trailing newlines (allowing `"""` syntax)
- make de-rst-ifying consistent across description and arguments
=> BF: more help improvements

onyo/lib/git.py
This limits git-commit calls to the paths that were requested to be
committed. Long standing issue, that I somehow keep forgetting about. Thanks, @aqw for making an issue about it ;-)
Closes #571
=> BF: Don't commit what onyo hasn't staged itself

CONTRIBUTING.md, README.md, docs/source/installation.rst, onyo/commands/config.py, onyo/commands/edit.py, onyo/commands/history.py, onyo/commands/init.py, onyo/commands/new.py, onyo/commands/shell_completion.py, onyo/commands/tree.py, onyo/shell_completion/zsh/_onyo
This PR is almost entirely improvements to the contents and formatting of help text. Lots was simply improved, and quite a few wrongs were righted. :-)
- `config`
- `edit`
- `history`
- `init`
- `shell-completion`
- `tree`
This PR also:
- removes the tab completion for the recently removed match options for `set` and `unset` (#557)
- fixes #569 
- fixes #456
=> DOC/BF: update a bunch more help text

onyo/commands/fsck.py, onyo/commands/get.py, onyo/commands/mkdir.py, onyo/commands/mv.py, onyo/commands/new.py, onyo/commands/rm.py, onyo/commands/set.py, onyo/commands/unset.py, onyo/lib/commands.py, onyo/shared_arguments.py
This PR finishes the tour of updating and reformatting the help text of the commands.
- `fsck`
- `get`
- `mkdir`
- `mv`
- `unset`
- `rm`
- `set`
This PR also:
- makes `new` match help conventions used in other commands
- fixes #396 
- fixes #449
=> BF/DOC: even more help-text fixes

onyo/main.py
This patch tries to workaround an issue with `argparse`, where an error on unrecognized arguments, is not associated with the selected subparser.
See https://bugs.python.org/issue34479
Solution here is, to rely on `parse_known_args` instead of `parse_args`, returning unrecognized arguments in a dedicated list and call the subparsers `print_usage` in addition to reproducing the toplevel parsers' error.
The reason for doing both, is because we can't distinguish `onyo -x new` from `onyo new -x` via argparse (we'd need to reparse `argv` ourselves). Hence, it's not clear in all cases, whether the usage for `new` or `onyo` would be relevant to the user.
So, in the above example this path ends up with:
```
❱ onyo -x new …
```
=> Fix help on unrecognized arguments

onyo/commands/rm.py
There was a missing character that let to a failure of the doc-build which I added.
=> add missing character to fix doc build error

onyo/commands/cat.py, onyo/commands/config.py, onyo/commands/edit.py, onyo/commands/fsck.py, onyo/commands/get.py, onyo/commands/history.py, onyo/commands/init.py, onyo/commands/mkdir.py, onyo/commands/mv.py, onyo/commands/new.py, onyo/commands/rm.py, onyo/commands/set.py, onyo/commands/shell_completion.py, onyo/commands/tests/test_onyo.py, onyo/commands/tests/test_set.py, onyo/commands/tests/test_unset.py, onyo/commands/tree.py, onyo/commands/unset.py, onyo/main.py, onyo/onyo_arguments.py, onyo/shared_arguments.py, setup.py
This PR:
- adds rich styling to help text
- don't leak RST-isms into CLI help text (fix #429)
- improves and normalize styling across help text 
- improves wording of some help text
This introduces a new dependency: `rich-argparse`
Sadly, there is no `rich.RST` analogue to `rich.Markdown`, so I intercept the help text, and convert relevant RST-isms into rich markup. It's not elegant, but functional.
Annoyingly, rich-argparse passes around rich `Text` objects rather than strings, which lacks basic string functionality. Thus, I need to intercept text at all three originating points, rather than the single rendering point.
If we want to remove the dependency, we could lift some pieces from the `rich-argparse` project (MIT licensed), and integrate our changes into them (flattening the …
=> DOC/BF: stylize help output with `rich`

demo/generate_demo_repo.sh, docs/source/cmd_new.rst, onyo/argparse_helpers.py, onyo/commands/cat.py, onyo/commands/config.py, onyo/commands/edit.py, onyo/commands/get.py, onyo/commands/history.py, onyo/commands/init.py, onyo/commands/mkdir.py, onyo/commands/mv.py, onyo/commands/new.py, onyo/commands/rm.py, onyo/commands/set.py, onyo/commands/tests/test_new.py, onyo/commands/tests/test_set.py, onyo/commands/tests/test_unset.py, onyo/commands/tree.py, onyo/commands/unset.py, onyo/lib/commands.py, onyo/lib/tests/test_commands_new.py, onyo/lib/tests/test_commands_set.py, onyo/lib/tests/test_commands_unset.py, onyo/onyo_arguments.py, onyo/shell_completion/zsh/_onyo, onyo/tests/test_usecases.py
These commands each used `--path`:
- `new`: -> `--path` (now matches the `directory` pseudo key)
- `set`: -> `--asset` (only operates on assets as of #557)
- `unset` -> `--asset` (only operates on assets as of #557)
This PR also:
- Removes no-op "types" from argparse that we were using to expose information to the tab completion script generation. That's all static now, so these are unused.
- Converts many short opts to long opts in the tests. They may the text more readable and thus self-documenting..
=> NF: rename misleading `--path` flag for `new`, `set`, and `unset`

onyo/commands/get.py, onyo/commands/tests/test_get.py, onyo/lib/commands.py, onyo/lib/onyo.py, onyo/lib/tests/test_commands_get.py, onyo/lib/tests/test_commands_new.py, onyo/lib/tests/test_inventory_operations.py, onyo/tests/test_usecases.py
This PR fixes the following bugs:
- #579 
- #583
- #578
- #592
As a brief digression... the test `test_onyo_get_reserved_keys()` ended up running into bug #583. Printing `path` twice exceeded the 80 char limit that Rich detects when running in a virtual TTY.
I looked into how to increase the faux-terminal width, but I could not find a reasonable way. [This rich bug](https://github.com/Textualize/rich/issues/317) was infuriatingly closed with no explanation, and the rich docs make no mention of `capsys`, and only `pytest` once...
Other suggestions involve [monkey patching `Popen`](https://stackoverflow.com/questions/60272369/pytest-monkeypatch-terminal-size), but it wasn't clear to me the right way to mock this through fixtures.
And at that point... I decided that if we don't want output …
=> BF: `onyo get` fixes

onyo/commands/tests/test_set.py, onyo/lib/git.py, onyo/lib/inventory.py, onyo/lib/onyo.py, onyo/lib/tests/test_commands_rm.py, onyo/lib/tests/test_git.py, onyo/lib/tests/test_onyo.py
I noticed these while looking into #322
This unifies the approach, and updates the doc strings.
=> BF/DOC: unify syntax of `OnyoRepo` and `GitRepo` `.clear_cache()`

onyo/cli/tests/test_new.py, onyo/cli/tests/test_onyo.py, onyo/cli/tests/test_set.py, onyo/cli/tests/test_unset.py, onyo/main.py, pyproject.toml
This has multiple advantages:
- drops a dependency (that is also unpackaged in Debian)
- `rst_to_rich()` is only used in the parser, thus rich markup no longer leaks into sphinx output
- fixes the "usage" section of sphinx output (which was garbled with CLI colorization syntax)
I also moved the commit from #616 to cleanup `main.py` that I missed in #615 that @TobiasKadelka pointed out.
=> DOC/BF: drop `rich_argparse` for home-grown solution

onyo/cli/cat.py, onyo/cli/config.py, onyo/cli/edit.py, onyo/cli/tests/test_cat.py, onyo/cli/tests/test_edit.py, onyo/cli/tests/test_get.py, onyo/cli/tests/test_history.py, onyo/cli/tests/test_rm.py, onyo/cli/tests/test_set.py, onyo/cli/tests/test_tree.py, onyo/cli/tests/test_unset.py, onyo/cli/tree.py, onyo/conftest.py, onyo/lib/command_utils.py, onyo/lib/commands.py, onyo/lib/differs.py, onyo/lib/executors.py, onyo/lib/git.py, onyo/lib/inventory.py, onyo/lib/onyo.py, onyo/lib/utils.py, onyo/main.py
This PR again focuses on docstrings, and then makes adjustments/cleanups that i encountered while focusing on them.
Docstring improvements:
- all of `command_utils.py`
- about 20% of `commands.py`
Non-docstring improvements include:
- `sanitize_args_config()` -> `allowed_config_args()`
- `onyo_edit()`'s behavior has been changed to match other onyo commands
- normalization of type checking imports
- normalization of some help text string declaration
Works towards:
- #489 
- #492 
- #493
=> DOC/TST/NF/RF: another collection of docstrings and general improvements

onyo/cli/rm.py, onyo/cli/tests/test_rm.py, onyo/lib/commands.py, onyo/lib/exceptions.py, onyo/lib/inventory.py, onyo/lib/tests/test_commands_rm.py, onyo/lib/utils.py, onyo/shell_completion/zsh/_onyo
Simplify the `rm` command, by removing the modes that would have the
command operate on asset or directory 'aspects' only. Instead have a
standard `--recursive` flag, making `onyo rm` aligned with standard
`rm`.
For only removing an aspect of an asset dir, `onyo set` is still
available.
Closes #596
=> `rm`: Replace modes with simple recursive flag

onyo/cli/tests/test_mkdir.py, onyo/lib/inventory.py, onyo/lib/tests/test_commands_mkdir.py, onyo/lib/tests/test_inventory_operations.py
This changes `onyo mkdir` to not fail on an existing non-inventory dir, but make it one instead.
Closes #597
=> `mkdir`: Allow adding existing non-inventory dirs

onyo/cli/new.py, onyo/cli/tests/test_new.py, onyo/lib/commands.py, onyo/lib/inventory.py, onyo/lib/onyo.py, onyo/lib/tests/test_onyo.py
Changes `new`'s `--template` parameter to accept actual paths rather than just names. If a path given is relative, it is first looked for underneath the template dir, maintaining the previous behavior when one gives a name of template file therein. Only, if that doesn't exist is a relative path resolved normally (CWD).
Closes #593
=> `new`: Allow actual paths for `--template`

onyo/cli/get.py, onyo/cli/new.py, onyo/cli/tests/test_get.py, onyo/cli/tests/test_new.py, onyo/lib/exceptions.py, onyo/main.py
Allow subcommands to fail on invalid arguments in a way
consistent with argparse, when the constraint can't be (or isn't anyway)
put into the argument specification dict.
Introduces a dedicated exception, that is handled to look like an
argparse error in `main.py`. Meaning: style of error reporting, printing
usage of subcommand and return code 2.
With that, allow `new`'s `-d/--directory` option only once.
Closes #539
=> Allow subcommands to fail on invalid arguments in a way consistent with argparse

onyo/lib/inventory.py, onyo/lib/tests/test_inventory_operations.py
This fixes the check for required keys with empty values to account for a possible `None`. Also move this check in `add_asset` and `modify_asset` after auto-generated values (faux-serials) but before name generation.
It's intentionally not integrated in the name generation for two reasons:
- While currently identical, required keys and keys used for name generation are conceptionally different. We could eventually allow for optional name fields.
- This type of validation needs refactoring to become cleaner and reduce code duplication. Narrower functions will make this more straight-forward.
Closes #594
=> Fix checks for non-empty, required keys

onyo/cli/tests/test_new.py, onyo/lib/inventory.py
(Forgot to add to PR #628)
Empty values for required keys (used in asset names) are currently forbidden. Re-enable the test accordingly and make the check report what keys actually are required.
Also change defined behavior on a TSV with no rows other than the header to report no assets created and return zero. The decisive thing here is to inform the user, but I think there's technically no error here - we were simply asked to do nothing.
=> Reenable test for missing values

onyo/cli/tests/test_edit.py, onyo/cli/tests/test_new.py, onyo/lib/commands.py, onyo/lib/ui.py
This allows to pose questions to the user in a more flexible way and make use of that by asking 3- and 4-way questions when editing assets (either via `onyo edit` or `onyo new --edit`).
`UI.request_user_response`  now takes a definition of a default answer and a list of specifications of possible answers.
The default is assumed when the user simply hits enter (empty response) or when `--yes` is set. Consequently this is rendering the name `yes` worse, but that may need to change anyway. We already established, that it's actually setting a non-interactive mode.
With that, we can now better deal with (bulk-) editing. See #553.
Closes #553
=> More flexible user questions

docs/source/configuration.rst, onyo/cli/config.py, onyo/cli/get.py, onyo/cli/new.py, onyo/cli/set.py, onyo/cli/unset.py, onyo/lib/commands.py, onyo/lib/consts.py, onyo/lib/inventory.py, onyo/lib/onyo.py, onyo/lib/tests/test_inventory_operations.py, onyo/lib/tests/test_onyo.py, onyo/main.py, onyo/skel/config, onyo/tests/demo/reference_git_log.txt
This PR renames the config that defines the asset naming scheme. Since this is a functional change of what's recorded in a repository and what to do with it, this becomes repository version 2 now.
Closes #572
I used the occasion to also introduce a first handling of different repository versions.
Onyo now fails on repositories with an unknown version.
Closes #441 
In addition, there's a bit of a shim in three places in order to translate the changed config name when running on a version 1 repo.
We'd want a way to actually (auto-)migrate repositories as well, but this is out of scope for this PR.
(See issue #633)
=> Rename asset name config

onyo/cli/tests/test_edit.py, onyo/lib/inventory.py, onyo/lib/onyo.py, onyo/lib/ui.py, onyo/lib/utils.py, onyo/main.py
This changes how onyo deals with errors when reading an asset file.
- A technically valid YAML that does not yield a dictionary is considered an invalid asset. This could be the case for a text file, that is not (yet) included in `.onyoignore`.
- At the lower level do not return an empty asset, but actually raise, if there was an error.
- When trying to read several assets (likely for matching) report such errors but do skip such a file and proceed.
- Have `UI` count when an error message is issued. With that `main.py` can exit non-zero if errors we reported even if no exception bubbled up, b/c the reporting code could proceed despite the error.
Closes #582
Closes #587
Closes #436
=> Rework error reporting on asset file content

docs/source/concepts.rst, docs/source/configuration.rst, onyo/cli/config.py, onyo/cli/edit.py, onyo/cli/tests/test_edit.py, onyo/lib/onyo.py
This changes the editor used by onyo to first fall back to git's editor before considering `$EDITOR` or `nano`.
Closes #347
Closes #536
=> Make `core.editor` first fallback

onyo/cli/tests/test_edit.py, onyo/lib/inventory.py, onyo/lib/utils.py
`modify_asset` raises a `NoopError` when there's nothing to do.
However, this was based on a dict comparison, leading to the assessment
that there isn't anything to do, if comments were the only thing
modified.
This commit adds a comparison helper, that accounts for `ruamel`'s
comment annotation. Builtin by `ruamel` operator overwrites (`__eq__`,
`__neq__`, `__contains__`) don't work for us, b/c a `CommentToken`'s
start- and end markers may end up being `FileMark` objects. And these
contain the path to a file this was read from. Hence, comparing across
files doesn't work as we need it to, b/c assets are edited in a temp
location, so that the edited asset object is connected to a different
file path. This led to edits that change nothing but comments being
ignored by `onyo edit` and …
=> Fixing asset comparison to account for comments

onyo/lib/inventory.py, onyo/onyo_arguments.py
This lets `add_directory` skip issuing an operation for parent dir
creation, if that's already in the operation queue.
Therefore, creating several dirs underneath the same to-be-created
parent don't execute, diff, and record that operation several times.
In addition, stumbled upon a minor bug, where we'd dump a full traceback when `CWD` happens to be gone.
Closes #538
=> `mkdir`: No duplicate creation of parent dirs

onyo/argparse_helpers.py, onyo/cli/get.py, onyo/cli/tests/test_get.py, onyo/lib/command_utils.py, onyo/lib/commands.py, onyo/lib/consts.py, onyo/lib/inventory.py, onyo/lib/onyo.py, onyo/lib/tests/test_commands_get.py, onyo/lib/tests/test_commands_tree.py, pyproject.toml
This addresses several issues with `get`, mostly on sorting.
See commit messages and closed issues for details.
In short:
- `get` now has `--exclude` and `--include` arguments, that take paths. Assets underneath these (or directly specified) are exclude or included in the query respectively. The previous `--path` argument is consequently an alias for `--include`.
- Sorting has changed. We have `-s` and `-S` for ascending and descending order. However, they now take a key to sort by as argument and can be given multiple times. Sorting by multiple keys is done in order of appearance, where ascending and descending is specified per key so that it can be a mix.
- Lastly, onyo now depends on `natsort` (and `fastnumbers`) rather than bothering to try and reinvent the wheel. This package already …
=> `get`: Better sorting and `--exclude`

onyo/lib/command_utils.py, onyo/lib/commands.py, onyo/lib/ui.py
This colorizes diffs in a git-like fashion.
Generally, that topic requires a more general solution, but this part is easy enough to have w/o making all issues relating to the use of `rich` a blocker.
Closes #581
=> Colorize diff output

onyo/lib/inventory.py, onyo/lib/onyo.py
This changes the parsing of key names used in the asset name config to include a literal dot in the key name. That way we can use the intended dot notation by putting a flattened dict into the yaml with literal keys like `disk.size: 250GB` and use it in asset names the same way (`"asset_name_{disk.size}"`). This temporary change would now report the literal key `disk.size` as required, rather than `disk`.
In addition this replaces any key reference in the config string by a proper python format-language reference
`asset[key_name_with_possible_dots]` because the format language does not allow arbitrary dictionary key names including dots, brackets and so on plus the dot has syntactical meaning. With this replacement, actual "dot features" can still be utilized.
=> TMP: Workaround not implemented dict support

onyo/lib/inventory.py, onyo/lib/utils.py
When reading from (edited) files, ruamel delivers a dict-like (`CommentedMap`). When accessed like a dict something like `serial: 00123` would show up as `{'serial': 123}`. However, under the hood ruamel retains the information how it was read (in roundtrip mode) and consequently dumps it as `serial: 00123`, which is what we want.
The issue is, that when using these dicts "normally", we end up looking at the "wrong" value - in this case an integer `123` - which messes up dumping into the asset name as well as dict comparisons when trying to find out whether there even was a modification.
This patch introduces a dict-like wrapper that delivers the representation ruamel would use for dumping rather than the "technical value" of that object.
The patch is considered temporary as it is …
=> TMP: Workaround YAML representation issue

onyo/lib/command_utils.py
Previously, sorting was case insensitive, so that the words would actually be grouped together. However, within a word, it was not sorted.
`GROUPLETTERS` does not do what we want, but using `LOCALE` does (at least with 'en_US.UTF-8').
For now, I am choosing to use whatever the user has configured on their OS. That makes sense to me, respecting their choice. If this ends up biting us in practice, then we'll simply hardcode it or make it a configurable option in `.onyo/config`.
fix #651
=> BF: make sorting case sensitive

onyo/shell_completion/zsh/_onyo
I don't quite know what I was trying to achieve here before, but with how we're currently using Onyo, the code seemed needlessly complicated.
Rarely, people report seeing the following when they first use `onyo new --template`:
```
onyo new -t (eval):1: command not found: _template_dir
```
I do not know what causes that, but it so far is unique to `_template_dir`.
These changes simplify it to work like other tab completion of files/dirs.
=> RF: simplify template tab completion

.github/workflows/tests.yaml
This adds the newly release Python 3.13 to the test matrix.
It also bumps the versions of various Actions. None of  them should bring in breaking changes.
=> TST: add Python 3.13; bump various Action versions

onyo/cli/tests/test_new.py, onyo/cli/tests/test_rm.py, onyo/cli/tests/test_set.py, onyo/cli/tests/test_unset.py, onyo/lib/commands.py, onyo/lib/inventory.py, onyo/lib/ui.py
This PR implements #656 
After the diff, and before the user prompt, the Inventory Operations is printed. This is the exact same summary that is included in the commit message.
A small, unrelated fix is also included, that adds spaces between user prompts and the response. This annoyed me greatly during my interactive tests. :-)
=> NF: print Inventory Operations after diff

onyo/lib/commands.py, onyo/lib/tests/test_commands_new.py, onyo/lib/tests/test_commands_set.py, onyo/lib/utils.py, onyo/shell_completion/zsh/_onyo
This PR has two unrelated fixes
- simplifies some unnecessary (and actively annoyingly) specific type annotations (#665)
- silences a one-time user error when first using shell completion (#585)
=> BF/TYPE: simplify some type checks; fix shell completion bug

onyo/cli/get.py, onyo/cli/tests/test_get.py, onyo/main.py
Previously, `onyo get` returned `1` if there was an error and `0` if not.
This change exits `2` on error, exits `1` if no results are found, and `0` if there are results found.
I considered adding a `returncode` attribute to exceptions, matching what `CalledProcessError` does. But how the CLI exits has nothing to do with exceptions. So I did the check there and categorically modified the behavior of `onyo get`.
close #680
=> NF: match `onyo get`'s exit codes to `grep`'s

onyo/argparse_helpers.py, onyo/lib/commands.py, onyo/lib/inventory.py, onyo/lib/onyo.py, onyo/lib/recorders.py, onyo/lib/tests/test_commands_new.py, onyo/lib/tests/test_utils.py, onyo/lib/ui.py, onyo/lib/utils.py
`os.linesep` is of no use to us, as git translates line endings to match the user's OS.
The codebase used both `linesep` and `\n`. It makes sense to choose the one that is 5-10 characters shorter, faster, and doesn't require an import.
This removes 9 out of 16 imports of `os`.
=> RF: `os.linesep` -> `\n`

onyo/lib/commands.py, onyo/lib/ui.py
This allows `onyo cat` to provide more value over using just `cat`.
Rich automatically detects if the TTY is interactive or not, so piping, etc is unaffected.
Works towards #55
=> NF: `onyo cat` use syntax highlighting for YAML

onyo/cli/edit.py, onyo/cli/mkdir.py, onyo/cli/mv.py, onyo/cli/new.py, onyo/cli/rm.py, onyo/cli/set.py, onyo/cli/tests/test_edit.py, onyo/cli/tests/test_mkdir.py, onyo/cli/tests/test_mv.py, onyo/cli/tests/test_new.py, onyo/cli/tests/test_rm.py, onyo/cli/tests/test_set.py, onyo/cli/tests/test_unset.py, onyo/cli/unset.py, onyo/lib/commands.py, onyo/lib/inventory.py, onyo/lib/onyo.py, onyo/lib/tests/__init__.py, onyo/lib/tests/test_commands_mkdir.py, onyo/lib/tests/test_commands_mv.py, onyo/lib/tests/test_commands_new.py, onyo/lib/tests/test_commands_rm.py, onyo/lib/tests/test_commands_set.py, onyo/lib/tests/test_commands_unset.py, onyo/lib/tests/test_onyo.py, onyo/lib/ui.py, onyo/shared_arguments.py, onyo/shell_completion/zsh/_onyo, onyo/tests/demo/reference_git_log.txt
=> Rework `--message` parameter

onyo/cli/cat.py, onyo/cli/get.py, onyo/cli/tests/test_cat.py, onyo/lib/commands.py, onyo/lib/exceptions.py, onyo/lib/tests/test_commands_cat.py, onyo/lib/ui.py, onyo/main.py, onyo/onyo_arguments.py
This continues my journey to bring more features to the most irrelevant parts of `onyo`. ;-)
Really, this was an accident. I was looking at #493 and chose to work on `cat`'s docstrings. There was ambiguity about error cases and invalid content, and I wanted to clarify it.
Previously, `onyo cat` would exit `0` on success and `1` on error (no print content) or invalid asset content (but still print content).
I really like `onyo get`'s new ability to differentiate between producing valid output that is problematic (exit `1`) vs an error (exit `2`). And so I chose to bring that to `onyo cat`. Invalid asset content will continue to print and exit `1`. Errors will now exit `2`.
I also introduce a new exception (`InvalidAssetError`), as I felt `OnyoInvalidRepoError` was misleading and was being …
=> NF/DOC: `onyo cat` improved documentation and enhance error codes

.flake8, .github/workflows/tests.yaml, onyo/lib/tests/test_commands_mkdir.py, pyproject.toml
[ruff](https://docs.astral.sh/ruff/) is a drop-in replacement for just about all Python linters.
It's blazingly fast (not an overstatement), and supports [far more rules](https://docs.astral.sh/ruff/rules/) than flake8.
This is a naive migration from flake8. More checks can be enabled as we see fit.
There is a github action for `ruff`. I didn't se the advantage of using it.
=> TST: flake8 -> ruff

docs/source/concepts.rst, docs/source/configuration.rst, onyo/cli/get.py, onyo/cli/tests/test_get.py, onyo/cli/unset.py, onyo/shell_completion/zsh/_onyo, onyo/tests/test_usecases.py
This PR
- fixes some outdated docs (in general, I'm leaving RTD alone for now, as it's so out of date)
- drops `onyo get --path`; it was an alias for `onyo get --include`
- it made the CLI feel inconsistent, and was confusing
- adds `--include` and `--exclude` to `onyo get`'s tab completion (somehow overlooked)
=> BF: retire `onyo get --path` alias, and other cleanups

.gitignore, CONTRIBUTING.md, onyo/conftest.py, onyo/lib/commands.py, onyo/lib/git.py, onyo/lib/tests/test_commands_cat.py, onyo/lib/tests/test_git.py, onyo/tests/benchmark.py, pyproject.toml
The core motivation for this PR is to add some benchmarks ~~and test out CodSpeed to see if it's a reasonable fit for us~~.
~~If not, the benchmarks are still useful, but we'll go back to vanilla pytest-benchmark. Codspeed is mostly compatible, until it isn't. For example, it does not support `pendantic`, which is a loss.~~
Generating large, representative repos led me to finally add Faker support. I hope/plan to use this for more tests that require populated repos, rather than our current verbose, hard-coded mess.
This PR also:
- fixes a bug in `git.get_hexsha()`
- fixes a documentation bug WRT flake8->ruff
- normalizes `onyo_cat()`'s arguments to match other onyo functions.
Fixes:
- #224 
- #254
I encountered numerous bugs around pytest fixture scoping, parametrization, indirect …
=> TST: add benchmarking and Faker support

onyo/argparse_helpers.py, onyo/cli/tests/test_set.py, onyo/lib/tests/test_inventory_operations.py, onyo/lib/tests/test_utils.py, onyo/lib/utils.py, onyo/tests/demo/reference_git_log.txt
See commit message.
This is essentially ready, but: It wouldn't be ready for a release or actual usage (which speaks to a lack of testing).
The reason is the `is_asset_directory` key, which is expected to be a boolean rather than a string.
But with this PR, users can't easily pass a boolean anymore.
However, the clean solution for that, would rely on a proper implementation of pseudo keys in general, so I'd prefer to solve the problem in that PR rather than here.
Closes #696
Closes #643
Closes #261
=> Getting rid of YAML implicit typing (for now)

onyo/cli/get.py, onyo/cli/new.py, onyo/cli/set.py, onyo/cli/tests/test_get.py, onyo/cli/tests/test_set.py, onyo/conftest.py, onyo/lib/command_utils.py, onyo/lib/commands.py, onyo/lib/consts.py, onyo/lib/differs.py, onyo/lib/executors.py, onyo/lib/inventory.py, onyo/lib/items.py, onyo/lib/onyo.py, onyo/lib/pseudokeys.py, onyo/lib/recorders.py, onyo/lib/tests/test_commands_cat.py, onyo/lib/tests/test_commands_get.py, onyo/lib/tests/test_commands_mv.py, onyo/lib/tests/test_commands_new.py, onyo/lib/tests/test_commands_rm.py, onyo/lib/tests/test_commands_set.py, onyo/lib/tests/test_commands_tree.py, onyo/lib/tests/test_commands_unset.py, onyo/lib/tests/test_inventory_operations.py, onyo/lib/tests/test_item.py, onyo/lib/tests/test_onyo.py, onyo/lib/tests/test_utils.py, onyo/lib/utils.py, onyo/tests/benchmark.py
Sits on top of PR #707 and resolves its issue WRT `is_asset_directory` by removing that key altogether. This is now split into the new `onyo.is.asset` and `onyo.is.directory` pseudo-keys. Although for the most part `onyo.is.directory` is what is used instead.
This is the first PR of a series, aiming to implement #662, #688, #689.
It's introducing an `Item` class and a new `PSEUDO_KEYS` mapping, that add pseudo-keys to dict-likes.
The aim for this PR is:
- Make `path` and `directory` keys aliases and replace their internal usage (except for test code, where they are still used at times in their role as default aliases)
- Remove `is_asset_directory` key in favor of `onyo.is.directory` (and `onyo.is.asset`)
- Replace `DotNotationWrapper` by `Item` in most places. `DotNotationWrapper` remains …
=> New pseudo-keys:  Part I

.readthedocs.yaml, onyo/conftest.py, onyo/lib/commands.py, onyo/lib/git.py, onyo/lib/inventory.py, onyo/lib/items.py, onyo/lib/onyo.py, onyo/lib/parser.py, onyo/lib/pseudokeys.py, onyo/lib/tests/test_commands_new.py, onyo/lib/tests/test_commands_set.py, onyo/lib/tests/test_inventory_operations.py, onyo/lib/tests/test_item.py, onyo/lib/utils.py
=> Pseudo-Keys Part II: history metadata

onyo/lib/command_utils.py, onyo/lib/commands.py, onyo/lib/tests/test_command_utils.py, onyo/tests/demo/reference_git_log.txt
It now generates more explicit and visually meaningful diffs between two paths (see #708).
Multi-path moves are not affected by this change.
Fixes:
- #708
- #709
Part of the broader effort for #475
=> NF/BF: support inline-diffs for `onyo mv`

onyo/conftest.py, onyo/lib/commands.py, onyo/lib/inventory.py, onyo/lib/tests/test_commands_mv.py, onyo/lib/tests/test_inventory_operations.py
This takes to approach of: minimal changes to make things work in areas of the code that are not ready to be flipped fully over to `Item()` yet.
This will lead to a bit of churn, but is the only rational way to convert the codebase incrementally rather than all at once.
=> RF: `Item()`-ize `onyo_mkdir()` and `inventory.add_directory()`

onyo/cli/tests/test_unset.py, onyo/conftest.py, onyo/lib/commands.py, onyo/lib/inventory.py, onyo/lib/items.py, onyo/lib/onyo.py, onyo/lib/tests/test_commands_get.py, onyo/lib/tests/test_commands_new.py, onyo/lib/tests/test_commands_set.py, onyo/lib/tests/test_commands_tree.py, onyo/lib/tests/test_commands_unset.py, onyo/lib/tests/test_inventory_operations.py, onyo/lib/tests/test_onyo.py, pytest.ini
- This enables `OnyoRepo` to be queried for paths of different types of items (Assets, Dirs, Templates) in preparation of the respective query modes for `onyo get` (see #673).
- In the process `Inventory.get_asset()` and `OnyoRepo.get_asset_paths()` are renamed b/c they account for all items, not just assets.
- Enhances the `onyorepo` fixture to take an `inventory_templates` marker
=> Allow querying OnyoRepo for paths of all kinds of items

onyo/cli/get.py, onyo/cli/tests/test_get.py, onyo/lib/commands.py, onyo/lib/inventory.py, onyo/lib/items.py, onyo/lib/tests/test_commands_get.py, onyo/lib/tests/test_inventory.py, onyo/lib/tests/test_item.py, onyo/shell_completion/zsh
This introduces the `--types` switch to `get`, allowing to specify what
types of items to consider for matching.
Closes https://github.com/psyinfra/onyo/issues/673
Closes https://github.com/psyinfra/onyo/issues/674
Closes https://github.com/psyinfra/onyo/issues/675
Closes https://github.com/psyinfra/onyo/issues/676
In the process fixed the `Item` class to account for templates and to have pseudokeys evaluate to `<unset>` for relative paths in `onyo.path.*` whenever they would point outside the repository.
=> `get`: Allow querying templates and directories

onyo/lib/items.py, onyo/lib/pseudokeys.py, onyo/lib/tests/test_item.py
This introduces `onyo.path.name` as a pseudo-key, providing the basename of an item's path for use in queries.
Sits on top of #750
=> New pseudo-key `onyo.path.name`

onyo/lib/commands.py, onyo/lib/inventory.py, onyo/lib/tests/test_inventory_operations.py
This is making sure `Inventory.modify_asset()`, `Inventory.rename_asset()`, and their callers pass `Item`s around rather than paths.
=> Itemize rename_asset and modify_asset

onyo/lib/commands.py, onyo/lib/executors.py, onyo/lib/inventory.py, onyo/lib/tests/test_commands_rm.py, onyo/lib/tests/test_inventory_operations.py
This ensures that the above mentioned `Inventory` methods are always passed `Item`s by their callers.
In the process two more aspects are addressed:
- Register both `remove_*` operations with an `Item` as operand.
- Change `onyo_rm` and `Inventory.remove_directory()` to not remove any non-inventory files regardless of `recursive`. What's `.onyoignore`'d is ignored by onyo. Period.
=> Itemize add_asset, remove_asset, remove_directory

docs/source/cmd_rmdir.rst, docs/source/command_line_reference.rst, onyo/cli/__init__.py, onyo/cli/rmdir.py, onyo/cli/tests/test_rmdir.py, onyo/lib/commands.py, onyo/lib/inventory.py, onyo/lib/tests/test_commands_mkdir.py, onyo/lib/tests/test_commands_rmdir.py, onyo/lib/tests/test_inventory_operations.py, onyo/main.py, onyo/shell_completion/zsh
It's the counterpart to `mkdir`. It removes empty directories and (more interestingly) converts asset directories into asset files.
fix #648
=> NF/DOC/TST: add `rmdir` command

.github/workflows/tests.yaml, onyo/cli/get.py, onyo/cli/mv.py, onyo/cli/new.py, onyo/cli/rmdir.py, onyo/cli/tests/test_get.py, onyo/cli/tests/test_unset.py, onyo/cli/tsv_to_yaml.py, onyo/conftest.py, onyo/lib/commands.py, onyo/lib/consts.py, onyo/lib/filters.py, onyo/lib/git.py, onyo/lib/onyo.py, onyo/lib/tests/test_Filter.py, onyo/lib/tests/test_commands_get.py, onyo/lib/tests/test_commands_mkdir.py, onyo/lib/tests/test_commands_mv.py, onyo/lib/tests/test_commands_new.py, onyo/lib/tests/test_commands_rm.py, onyo/lib/tests/test_git.py, onyo/lib/tests/test_utils.py, onyo/lib/utils.py, onyo/tests/demo/test_generate_demo_repo.py, pyproject.toml
The primary purpose of this is to allow filtering numerical fields (e.g. `cpu.cores < 4`, etc). However, we get string comparisons for free as well, so filtering according to alphabetical order, etc, is possible (e.g. `type>laptop`).
fixes #719
=> NF/TST: add `<`, `<=`, `>`, and `>=` support to `--match` 

onyo/argparse_helpers.py, onyo/cli/get.py, onyo/cli/tests/test_get.py, onyo/lib/commands.py, onyo/lib/inventory.py, onyo/lib/tests/test_item.py, onyo/lib/tests/test_utils_dotnotationwrapper.py, onyo/lib/utils.py
The big feature is enabling `onyo get` to have multiple `--match` invocations. This allows for an "OR" operator in addition to what was previously just "AND".
The behavior is the exact same as before, and this feature is the equivalent of running multiple `onyo get` statements and deduplicating the results. Having this supported directly in `onyo get` is more performant, and saves the user the effort of deduplicating and re-sorting the merged outputs.
An unrelated (but annoying) bug was fixed, WRT to querying subkeys of a missing key.
fix #361
fix #649
fix #697
=> BF/NF/TST/DOC: allow multiple `onyo get --match` statements (enabling OR)

.github/workflows/tests.yaml, .readthedocs.yaml, CONTRIBUTING.md, README.md, docs/source/installation.rst, onyo/argparse_helpers.py
This bumps the baseline Python version from 3.11 to 3.13.
In the future, we won't bump so aggressively. But while developing, there is little incentive to support versions that we are not running and have little intention of supporting.
I also bumped the ReadTheDocs build environment.
=> Bump python baseline from 3.11 -> 3.13

onyo/lib/commands.py, onyo/lib/git.py, onyo/lib/tests/test_git.py, pyproject.toml
Though `GitRepo.check_ignore()` allows a list of paths to be passed, upper levels of Onyo only ever check one path at a time.
This inefficiency was made even more expensive, as each call spawned a subprocess for `git check-ignore` to check the path against the ignore file.
On our internal repository, this caused over 1,100 calls to `git check-ignore` for a single `onyo get` call.
Thankfully, there is a (seemingly) mature project (pathspec) that understands the patterns used in git ignore files.
Here, I swap out `git check-ignore` for pathspec.
In our internal inventory repository (which has three `.onyoignore` files), it brought that same `onyo get` call (with 1,100 `git check-ignore` invocations) down from an average of 2.80s to 1.18s.
I would love to show numbers from the benchmarking …
=> BF/RF: use pathspec module for `.{git,onyo}ignore` files

onyo/cli/tests/test_edit.py, onyo/lib/commands.py, onyo/lib/git.py, onyo/lib/onyo.py, onyo/lib/tests/test_git.py, onyo/lib/utils.py
Fixes in this PR are:
1) don't error when creating a boatload of assets and thus overflowing the maximum command length (#727) 
2) introduce caching for `OnyoRepo.get_config()`
3) cleanup around temp files (dangling file handles, leaked paths, etc)
---
Regarding 1: I introduced a test to overflow with paths (since the overflow can happen with either the message or paths), but left it disabled by default because it takes 30+ minutes to run on my machine. The paths need to be relatively short (beneath the size of the most limiting OS/FS) in order to run reliably. And then in total exceed the maximum argument length of the most capable OS/FS. This results in 150k+ files, and that understandably takes a long time to run.
So the test is there for reference if we are ever uncertain. But is …
=> BF/RF: fix command length overflow; cache `OnyoRepo.get_config()`

onyo/lib/command_utils.py, onyo/lib/inventory.py, onyo/lib/onyo.py, onyo/lib/tests/test_utils.py, onyo/lib/utils.py
This is preparing the YAML tooling for multidoc, layered, recursive templates for the envisioned change to the `new` command.
- Enables asset files to contain multiple documents as "sidecars" (everything but the first doc is ignored by onyo, but multidoc is valid content that doesn't crash anything).
- Have generic YAML writing/reading that doesn't come with asset contraints in preparation of reading YAML input that can contain pseudo-keys.
- Proof-of-concept functions to demonstrate how `onyo show` and `onyo new` would deal with a YAML description of an inventory tree
=> Enhance YAML tooling

onyo/cli/tests/test_get.py, onyo/cli/tests/test_set.py, onyo/cli/tests/test_unset.py, onyo/conftest.py, onyo/lib/command_utils.py, onyo/lib/commands.py, onyo/lib/differs.py, onyo/lib/executors.py, onyo/lib/inventory.py, onyo/lib/items.py, onyo/lib/onyo.py, onyo/lib/pseudokeys.py, onyo/lib/tests/test_commands_new.py, onyo/lib/tests/test_item.py, onyo/lib/tests/test_items_ItemSpec.py, onyo/lib/tests/test_utils.py, onyo/lib/utils.py, onyo/tests/benchmark.py
This PR got way more complicated than I expected it to.
The primary feature is:
- rename DotNotationWrapper to ItemSpec
- move a lot of Item's functionality into ItemSpec
This lays down the groundwork to eventually require that all `Item`s have a `repo` and have sanity checks on init.
This also includes some other unrelated fixes:
- Itemification of various functions
- make `faux_serials()` lowercase only
- ItemSpec is meant to be used to load YAML strings and dump YAML.
=> RF: DotNotationWrapper -> ItemSpec

onyo/lib/inventory.py
A hack, until the new `new` shows up. :-)
fix #785
=> BF: regenerate `onyo.path.relative` pseudokey in `inventory.add_asset()`

onyo/lib/commands.py, onyo/lib/onyo.py
Running (for example) `onyo new --message haha` would not put a blank line between the auto-generated subject and the user-provided message. Thus the first message was part of the subject, which is not desired.
Git strips trailing newlines, so there's need to detect if there's a follow-up message or not.
=> BF: ensure first `--message` is not part of the subject
