psyinfra/onyo

- README.md
> remove `onyo anchor`

- README.md
> document onyo mkdir

- README.md
> document onyo rm

- .flake8
- .github/workflows/main.yml
- onyo/commands/anchor.py
- onyo/commands/edit.py
- onyo/commands/git.py
- onyo/commands/init.py
- onyo/commands/mv.py
- onyo/commands/new.py
- onyo/commands/unanchor.py
- onyo/main.py
- tests/default_tests.py
CI will be triggered with pushs and PRs.
Adds linting with flake8, and a flake8 config file (specifies which rules are to follow/ignore) and updates code base to these rules.
This is an updated fork, it contains the changes requested in: https://github.com/psyinfra/onyo/pull/63
> CI: trigger with PR, add flake8 linting

- onyo/commands/new.py
Before, all fields were checked, now the function that reads words
has a new parameter to disable the check for reserved characters.
> new: serial field has no restrictions for characters

- onyo/commands/__init__.py
- onyo/commands/rm.py
- onyo/main.py
- tests/default_tests.py
- tests/output_goals/test_1/delete_device.txt
- tests/output_goals/test_2/delete_device.txt
- tests/output_goals/test_3/delete_device.txt
- tests/output_goals/test_4/delete_device.txt
- tests/output_goals/test_tree_output.txt
This adds `onyo rm` as a subcommand (rm.py, and modifications in
main.py and __init__.py), and adds onyo rm to the tests.
close #73
> rm: add function and tests

- README.md
After discussions, updates and changes in onyos behaviour, the readme needed to be updated, and mistakes in it were corrected too.
> Clean and Update the Readme

- onyo/commands/__init__.py
- onyo/commands/fsck.py
- onyo/main.py
- setup.py
This adds the command to onyos main.py and __init__.py.
Additionally adds pyyaml to setup.py for the yaml syntax check.
> fsck: add command

- onyo/commands/__init__.py
- onyo/commands/config.py
- onyo/commands/history.py
- onyo/commands/init.py
- onyo/main.py
In #6 the implementation, options and other decissions were discussed.
Close #6
This adds the commands `onyo history`, and also `onyo config`, which sets the config variables that `onyo history` uses.
> Add commands: history and config

- onyo/utils.py
> wrap descriptions in help text

- onyo/commands/fsck.py
- onyo/commands/history.py
- onyo/commands/init.py
- onyo/commands/mkdir.py
- onyo/commands/mv.py
- onyo/commands/new.py
- onyo/commands/rm.py
- onyo/commands/set.py
- onyo/utils.py
This is a collection of various doc fixes. The most interesting of which is the removal of redundant descriptions of opt-flags in docstrings.
> DOC: Assorted fixes

- docs/source/installation.rst
> docs: add non-python dependencies to installation instructions

- tests/test_init.py
- tests/test_mkdir.py
The adds tests for `mkdir`, and refactors a bit for both `mkdir` and `init`.
> TST: Assorted improvements

- onyo/commands/rm.py
- onyo/utils.py
- tests/output_goals/test 1/delete_device.txt
- tests/output_goals/test 2/delete_device.txt
- tests/test_main.py
- tests/test_rm.py
This adds tests for `rm` and also refactors the command to improve readability and docs.
> Refactor `rm`

- onyo/utils.py
These are no longer referenced anywhere.
> BF: remove unused functions

- .readthedocs.yaml
- docs/source/changelog.rst
- docs/source/conf.py
> DOC: make RTD build fail on warnings

- README.md
Add sections for:
* users (with link to install instructions in docs)
* reporting issues
* developers (with instructions for install, tests, and docs)
Fixes #177
> DOC: reorg README

- onyo/__init__.py
- onyo/commands/cat.py
- onyo/commands/config.py
- onyo/commands/edit.py
- onyo/commands/fsck.py
- onyo/commands/history.py
- onyo/commands/init.py
- onyo/commands/mkdir.py
- onyo/commands/mv.py
- onyo/commands/new.py
- onyo/commands/rm.py
- onyo/commands/set.py
- onyo/commands/shell_completion.py
- onyo/commands/tree.py
- onyo/main.py
- onyo/utils.py
- setup.py
- tests/commands/test_cat.py
- tests/commands/test_history.py
- tests/commands/test_init.py
- tests/commands/test_mv.py
- tests/commands/test_new.py
- tests/commands/test_rm.py
- tests/test_invoking.py
This is an assortment of random cleanup that I kept tripping over, and I don't want to lose track of, so I'm bundling them all together into the same PR.
The most invasive change is renaming `logger` -> `log`, for the sake of brevity.
> RF: assorted cleanup

- demo/generate_demo_repo.sh
> add framework of demo script

- demo/generate_demo_repo.sh
- demo/inventory.tsv
Add a list of onyo commands to `generate_demo_repo.sh`, and `inventory.tsv` for the command `onyo new -y --tsv inventory.tsv`
> DEMO: add example workflow to build an inventory

- demo/generate_demo_repo.sh
And change the order of a few commits.
> DEMO: cleanup some comments

- onyo/commands/edit.py
- onyo/commands/set.py
- onyo/commands/unset.py
- onyo/lib/onyo.py
The function restores all committed changes, e.g. if user responds with "no" to promt when asked if assets should be updated.
Close #258
> NF: add function `Repo.restore()`

- onyo/lib/onyo.py
- tests/lib/test_Repo_fsck.py
Adds the check to `Repo.fsck()`, and adds tests.
Close #283
> NF: add fsck check for pseudo-key names in the asset file

- docs/source/changelog.rst
This adds to the changelog for Release 0.4.0 all changes and updates (as of Monday the 17. April) since the last release 0.3.0!
> Release 0.4.0

- onyo/lib/command_utils.py
- onyo/lib/onyo.py
- onyo/lib/utils.py
> RF lib - Step 1

- onyo/lib/assets.py
- onyo/lib/command_utils.py
- onyo/lib/commands.py
- onyo/lib/git.py
- onyo/lib/onyo.py
> Remove superfluous exception logs

- onyo/lib/assets.py
- onyo/lib/filters.py
- onyo/lib/test/test_Filter.py
`read_asset` and `write_asset` were mere "redirects". Not needed anymore.
> Remove shim functions

- onyo/commands/tests/test_new.py
Changes:
- Adds tests for different path situations for `onyo new`:
- test from a subdirectory of the repository with _absolute_ paths
- test from a subdirectory of the repository with _relative_ paths
TODOs (already described in the issues listed below):
- add tests for different paths to other CLI tests (like done for `onyo new`)
- add tests with `onyo -C` to CLI tests
This works into the direction of #142 and #206
> TST: add tests for rel/abs paths and from different locations

- README.md
https://github.com/psyinfra/onyo/issues/339
> DOC: declare numpy as the docstring style

- onyo/commands/tests/test_init.py
- onyo/lib/git.py
- onyo/lib/onyo.py
Close #305 "BUG: onyo init prints into stderr on success"
> BF/init: onyo init prints now into stdout, not stderr

- onyo/lib/recorders.py
> Remove indentation from op records

- onyo/argparse_helpers.py
- onyo/main.py
> Fix ctrl c

- onyo/commands/set.py
> DOC: fix typo

- onyo/commands/edit.py
- onyo/commands/mkdir.py
- onyo/commands/mv.py
- onyo/commands/new.py
- onyo/commands/rm.py
- onyo/commands/set.py
- onyo/commands/unset.py
> BF: match git's behavior for multiple invocation of `-m`

- onyo/commands/tests/test_init.py
- onyo/lib/commands.py
- onyo/lib/differs.py
- onyo/lib/git.py
- onyo/lib/onyo.py
Solves inconsistencies and ambiguities in messages displayed to the user.
Close https://github.com/psyinfra/onyo/issues/423
Close https://github.com/psyinfra/onyo/issues/430
Close https://github.com/psyinfra/onyo/issues/442
> User messages

- onyo/commands/tests/test_unset.py
- onyo/commands/unset.py
- onyo/lib/commands.py
> unset: refactor command; adjust tests

- onyo/lib/git.py
This patch changes the `GitRepo.get_subtrees` method to use `git ls-tree` instead of `git ls-files`, in order to consistently only consider committed files instead of what's in the worktree. This was missed when addressing issue #502.
There's a corner case when a repository doesn't have a commit and
therefore no HEAD. Returning an empty list is just fine in that case.
Therefore, catch the error and pretend the output was empty.
> BF: Consider committed files only

- onyo/lib/commands.py
- onyo/lib/inventory.py
- onyo/lib/tests/test_commands_mv.py
> `mv`: Allow to move into existing dir with same name

- onyo/lib/inventory.py
- onyo/lib/tests/test_commands_rm.py
- Fixes `onyo rm` to account for already pending removals. This should be done more consistently (see #546).
- Fixes `onyo rm` to fail when trying to remove the inventory's root dir.
Note, that changes in `Inventory.remove_directory` are mostly about recursive removal of directories. For example, changing a condition to recursively call itself on `path.is_dir` rather than considering `is_inventory_dir` is done, because the latter, more restrictive condition would be checked again during recursion anyway.
Refactoring of the "dummy operation" for generic file removal is done, so it can be easily accounted for by `Inventory._get_pending_removals`, which would be harder to do if it remained that unnamed ad-hoc operation.
Lastly, note that the unskipped test's referral to #309 was wrong to …
> BF: `rm` handles duplication and fails on inventory root

- onyo/skel/templates/laptop.example
- onyo/tests/demo/reference_git_log.txt
close #584
Updates the example template to match documentation, and updates the git reference log for the demo too (which of course changed because of the changed template).
Since generating the demo worked now for me, this PR also verified that the changes of #602 did in fact resolve the problem described in #591.
> BF: update template example to match documentation

- onyo/argparse_helpers.py
- onyo/cli/new.py
- onyo/cli/set.py
- onyo/cli/tests/test_set.py
> NF: add StoreSingleKeyValuePair for `onyo set`

- onyo/main.py
This primarily adds docstrings and comments to `onyo/main.py`. it also does some very light refactoring, to improve clarity.
> DOC/RF: add docstrings to `onyo/main.py`

- onyo/cli/tests/test_set.py
- onyo/cli/tests/test_unset.py
- onyo/lib/differs.py
- onyo/lib/exceptions.py
- onyo/lib/inventory.py
This is an assortment of small fixes I have locally, that were leftover from when I was working on Onyo last.
I'm throwing these together in a PR to get them off my machine, reduce conflicts, etc.
> Assorted Jazz

- onyo/lib/commands.py
- onyo/lib/inventory.py
This fixes a couple of bugs concerning empty keys (not empty values) and the usage of reserved and/or pseudo keys with onyo commands.
Closes #535
> More fixes WRT invalid keys

- demo/generate_demo_repo.sh
> More specific error messages on demo generation

- onyo/cli/tests/test_new.py
- onyo/lib/commands.py
> BF: allow `onyo new` with just `--clone` or `--template`

- onyo/lib/filters.py
- onyo/lib/utils.py
There's no functional change in this patch. Just refactoring the code to be a bit simpler, slightly more efficient and (most importantly) a little easier to read and maintain. Previous version of the implementation was a bit convoluted as pointed out in https://github.com/psyinfra/onyo/pull/668#discussion_r1798456545
> Simplify Filter.match

- onyo/lib/exceptions.py
- onyo/lib/ui.py
- onyo/main.py
> Better error when failing to read user input

- onyo/cli/tests/test_edit.py
- onyo/lib/command_utils.py
- onyo/lib/commands.py
- onyo/lib/consts.py
- onyo/lib/exceptions.py
- onyo/lib/git.py
- onyo/lib/inventory.py
- onyo/lib/items.py
- onyo/lib/onyo.py
- onyo/lib/pseudokeys.py
- onyo/lib/tests/test_git.py
- onyo/lib/tests/test_inventory_operations.py
- onyo/lib/tests/test_onyo.py
- pyproject.toml
This was an accidental adevnture while I was working on something else. I was motivated for a time to improve docstrings, and so i ran with it while I had the motivation.
When I work on docstrings, I usually do a review (of varying depth) of the code it covers. Thus, there are a few code changes sprinkled in here as well.
And then a few more functions in `inventory.py` have been `Item`-ized.
> DOC/RF: Lots of docstrings; some `Item`-ization

- onyo/conftest.py
- onyo/lib/commands.py
- onyo/lib/inventory.py
- onyo/lib/items.py
- onyo/lib/onyo.py
- onyo/lib/tests/test_onyo.py
- onyo/lib/utils.py
- onyo/tests/templates/asset_dir/.onyo-asset-dir
- onyo/tests/templates/asset_dir/asset1
- onyo/tests/templates/asset_dir/subdir/asset3
- onyo/tests/templates/empty_template_dir_file
- onyo/tests/templates/template_dir/asset1
- onyo/tests/templates/template_dir/asset2
- onyo/tests/templates/template_dir/subdir/asset3
- onyo/tests/templates/template_dir_file
> Recursive (directory) templates

- docs/source/cmd_show.rst
- docs/source/command_line_reference.rst
- onyo/cli/__init__.py
- onyo/cli/show.py
- onyo/lib/command_utils.py
- onyo/lib/commands.py
- onyo/main.py
- onyo/shell_completion/zsh
This provides a simple version of `onyo show` (and a few unrelated bug fixes and cleanups).
> NF: `onyo show`
